export interface ReferenceSeedInput{readonly seed:number;readonly businessRows:number;readonly baseline:string;readonly passwordDigests:Readonly<Record<'dispatcher'|'operator'|'reviewer'|'administrator',string>>}
export interface ReferenceSeed{readonly formatVersion:'1.0';readonly seedId:string;readonly baseline:string;readonly users:readonly Readonly<{username:string;displayName:string;roleId:string;passwordDigest:string}>[];readonly recordOrder:readonly string[];readonly records:Readonly<Record<string,readonly Readonly<Record<string,unknown>>[]>>;readonly report:Readonly<{countedBusinessRows:number;counts:Readonly<Record<string,number>>;cohorts:Readonly<{abnormalOpen:number;closed:number}>}>}
const pad=(n:number)=>String(n).padStart(3,'0');
function time(base:number,minutes:number){return new Date(base+minutes*60_000).toISOString();}
export function generateReferenceSeed(input:ReferenceSeedInput):ReferenceSeed{if(!Number.isSafeInteger(input.seed)||input.seed<0||input.seed>0xffffffff)throw new Error('seed must be an unsigned 32-bit integer.');if(input.businessRows!==1000)throw new Error('Reference seed requires exactly 1000 business rows.');const base=Date.parse(input.baseline);if(!Number.isFinite(base)||new Date(base).toISOString()!==input.baseline)throw new Error('baseline must be an exact ISO timestamp.');const records:Record<string,Array<Record<string,unknown>>>={asset_category:[],asset:[],asset_responsibility:[],asset_event:[],service_catalog:[],sla_policy:[],work_order:[],work_order_event:[],inspection_plan:[],inspection_task:[],inspection_item:[],inspection_event:[],inspection_work_order_link:[]};
for(let i=1;i<=10;i++)records.asset_category!.push({code:`CAT-${pad(i)}`,name:`设备分类 ${pad(i)}`,active:true});
for(let i=1;i<=120;i++){const code=`AST-${pad(i)}`,status=i>110?'inactive':i>100?'maintenance':'active';records.asset!.push({code,name:`设备 ${pad(i)}`,category_code:`CAT-${pad((i-1)%10+1)}`,status,location:`区域 ${((i-1)%8)+1}`});records.asset_responsibility!.push({code:`RESP-${pad(i)}`,asset_code:code,assignee:`责任岗位-${pad((i-1)%20+1)}`,started_at:time(base,-50000+i),ended_at:null,active:true});records.asset_event!.push({code:`AEVT-${pad(i)}`,asset_code:code,event_type:'created',from_status:null,to_status:'active',reason:'初始化纳管',occurred_at:time(base,-50000+i)});}
for(let i=1;i<=5;i++)records.service_catalog!.push({code:`SVC-${pad(i)}`,name:`运维服务 ${i}`,description:'离线运维服务',active:true});const priorities=['low','normal','high','urgent']as const;for(let s=1;s<=5;s++)for(let p=0;p<4;p++)records.sla_policy!.push({code:`SLA-${pad((s-1)*4+p+1)}`,name:`服务 ${s} ${priorities[p]} 策略`,service_code:`SVC-${pad(s)}`,priority:priorities[p],response_minutes:30*(p+1),resolution_minutes:240*(p+1),active:true});
const workStatuses=['pending_dispatch','pending_acceptance','processing','pending_review','closed']as const;for(let i=1;i<=150;i++){const status=workStatuses[(i-1)%5]!,priority=priorities[(i-1)%4]!,service=(i-1)%5+1,policy=(service-1)*4+priorities.indexOf(priority)+1,created=time(base,-20000+i);records.work_order!.push({code:`WO-${pad(i)}`,title:`设备工单 ${pad(i)}`,description:'确定性运维处理事项',service_code:`SVC-${pad(service)}`,sla_policy_code:`SLA-${pad(policy)}`,priority,status,requester_id:'dispatcher',handler_id:status==='pending_dispatch'?null:'operator',resolution:status==='pending_review'||status==='closed'?'处理完成':null,response_due_at:time(Date.parse(created),60),resolution_due_at:time(Date.parse(created),480),accepted_at:['processing','pending_review','closed'].includes(status)?time(Date.parse(created),30):null,submitted_at:['pending_review','closed'].includes(status)?time(Date.parse(created),120):null,closed_at:status==='closed'?time(Date.parse(created),180):null,asset_code:`AST-${pad((i-1)%100+1)}`});records.work_order_event!.push({code:`WOEVT-${pad(i)}`,work_order_code:`WO-${pad(i)}`,event_type:'created',from_status:null,to_status:'pending_dispatch',actor_id:'dispatcher',content:'创建工单',occurred_at:created});}
for(let i=1;i<=30;i++)records.inspection_plan!.push({code:`PLAN-${pad(i)}`,name:`设备巡检计划 ${pad(i)}`,cycle_days:(i%30)+1,instructions:'按检查项逐项执行',active:true,asset_code:`AST-${pad(i)}`});
const taskStatuses=['pending','executing','pending_review','archived']as const;for(let i=1;i<=100;i++){const status=taskStatuses[(i-1)%4]!,scheduled=time(base,-10000+i*10);records.inspection_task!.push({code:`TASK-${pad(i)}`,plan_code:`PLAN-${pad((i-1)%30+1)}`,title:`设备巡检任务 ${pad(i)}`,status,executor_id:'operator',scheduled_at:scheduled,started_at:status==='pending'?null:time(Date.parse(scheduled),10),submitted_at:['pending_review','archived'].includes(status)?time(Date.parse(scheduled),30):null,archived_at:status==='archived'?time(Date.parse(scheduled),60):null,asset_code:`AST-${pad((i-1)%30+1)}`});}
for(let i=1;i<=150;i++){const abnormal=i<=10,task=(i-1)%100+1;records.inspection_item!.push({code:`ITEM-${pad(i)}`,task_code:`TASK-${pad(task)}`,name:`检查项 ${pad(i)}`,standard:'状态正常',result:abnormal?'abnormal':'normal',finding:abnormal?'发现异常':null,disposition:abnormal?'转整改工单':null,checked_at:time(base,-9000+i),});}
for(let i=1;i<=20;i++)records.inspection_event!.push({code:`IEVT-${pad(i)}`,task_code:`TASK-${pad(i)}`,event_type:'created',from_status:null,to_status:'pending',actor_id:'dispatcher',content:'创建巡检任务',occurred_at:time(base,-10000+i*10)});
for(let i=1;i<=5;i++)records.inspection_work_order_link!.push({code:`IWL-${pad(i)}`,inspection_task_code:`TASK-${pad(i)}`,inspection_item_code:`ITEM-${pad(i)}`,work_order_code:`WO-${pad(i)}`,payload_digest:String(input.seed).padStart(64,String(i)),created_at_business:time(base,-8000+i)});
const recordOrder=Object.freeze(Object.keys(records)),counts=Object.freeze(Object.fromEntries(recordOrder.map(id=>[id,records[id]!.length]))),total=Object.values(counts).reduce((a,b)=>a+b,0);if(total!==1000)throw new Error(`Reference seed produced ${total} rows instead of 1000.`);const users=Object.freeze([{username:'dispatcher',displayName:'调度人员',roleId:'work_order_dispatcher',passwordDigest:input.passwordDigests.dispatcher},{username:'operator',displayName:'处理人员',roleId:'inspection_executor',passwordDigest:input.passwordDigests.operator},{username:'reviewer',displayName:'复核人员',roleId:'work_order_reviewer',passwordDigest:input.passwordDigests.reviewer},{username:'administrator',displayName:'系统管理员',roleId:'asset_admin',passwordDigest:input.passwordDigests.administrator}].map(Object.freeze));return Object.freeze({formatVersion:'1.0',seedId:`reference-${input.seed}`,baseline:input.baseline,users,recordOrder,records:Object.freeze(Object.fromEntries(recordOrder.map(id=>[id,Object.freeze(records[id]!.map(Object.freeze))]))),report:Object.freeze({countedBusinessRows:total,counts,cohorts:Object.freeze({abnormalOpen:4,closed:1})})});}
