import type { DatabaseSync } from 'node:sqlite';
import { AppError } from '../../../../desktop-runtime/src/shared/errors';
import type { AssetLifecycleBlocker } from '../../asset_registry/runtime/index';
import { InspectionService } from '../../inspection_rectification/runtime/inspection-service';
import type { CreateInspectionPlanRequest, CreateInspectionTaskRequest, InspectionContext, InspectionPlanResult, InspectionTaskResult } from '../../inspection_rectification/runtime/types';

export interface CreateAssetInspectionPlanRequest extends CreateInspectionPlanRequest { readonly assetId:number }
export interface AssetInspectionHistory { readonly taskId:number;readonly taskCode:string;readonly title:string;readonly status:string;readonly scheduledAt:string;readonly archivedAt:string|null }

function activeAsset(assetId:number,connection:DatabaseSync){const row=connection.prepare('SELECT code,status FROM biz_asset WHERE id=?').get(assetId)as{code:string;status:string}|undefined;if(!row)throw new AppError('NOT_FOUND','Linked asset was not found.');if(row.status!=='active')throw new AppError('INVALID_TRANSITION','Inspection tasks require an active asset.');return row;}

export function createAssetInspectionPlan(request:CreateAssetInspectionPlanRequest,context:InspectionContext):InspectionPlanResult{const asset=activeAsset(request.assetId,context.connection);const result=new InspectionService().createPlan({name:request.name,cycleDays:request.cycleDays,instructions:request.instructions,active:request.active},context);const update=context.connection.prepare('UPDATE biz_inspection_plan SET asset_code=? WHERE id=? AND asset_code IS NULL').run(asset.code,result.planId);if(Number(update.changes)!==1)throw new AppError('VERSION_CONFLICT','Inspection plan asset relation could not be saved.');return result;}

export function createAssetInspectionTask(request:CreateInspectionTaskRequest,context:InspectionContext):InspectionTaskResult{const plan=context.connection.prepare('SELECT asset_code FROM biz_inspection_plan WHERE code=?').get(request.planCode)as{asset_code:string|null}|undefined;if(!plan)throw new AppError('NOT_FOUND','Inspection plan was not found.');if(!plan.asset_code)throw new AppError('VALIDATION_FAILED','Inspection plan is not linked to an asset.');const asset=context.connection.prepare('SELECT id,status FROM biz_asset WHERE code=?').get(plan.asset_code)as{id:number;status:string}|undefined;if(!asset||asset.status!=='active')throw new AppError('INVALID_TRANSITION','Inspection tasks require an active asset.');const result=new InspectionService().createTask(request,context);const update=context.connection.prepare('UPDATE biz_inspection_task SET asset_code=? WHERE id=? AND asset_code IS NULL').run(plan.asset_code,result.taskId);if(Number(update.changes)!==1)throw new AppError('VERSION_CONFLICT','Inspection task asset relation could not be saved.');return result;}

export function createOpenInspectionAssetBlocker():AssetLifecycleBlocker{return(assetId,connection)=>{const asset=connection.prepare('SELECT code FROM biz_asset WHERE id=?').get(assetId)as{code:string}|undefined;if(!asset)return{blocked:false,code:'ASSET_NOT_FOUND',message:''};const row=connection.prepare("SELECT COUNT(*) count FROM biz_inspection_task WHERE asset_code=? AND status!='archived'").get(asset.code)as{count:number};return Number(row.count)>0?{blocked:true,code:'ASSET_HAS_UNARCHIVED_INSPECTIONS',message:'Asset has unarchived inspections.'}:{blocked:false,code:'ASSET_INSPECTIONS_ARCHIVED',message:''};};}

export function readAssetInspectionHistory(assetId:number,connection:DatabaseSync):readonly AssetInspectionHistory[]{const asset=connection.prepare('SELECT code FROM biz_asset WHERE id=?').get(assetId)as{code:string}|undefined;if(!asset)throw new AppError('NOT_FOUND','Asset was not found.');return Object.freeze((connection.prepare('SELECT id,code,title,status,scheduled_at,archived_at FROM biz_inspection_task WHERE asset_code=? ORDER BY scheduled_at DESC,id DESC').all(asset.code)as any[]).map(row=>Object.freeze({taskId:Number(row.id),taskCode:String(row.code),title:String(row.title),status:String(row.status),scheduledAt:String(row.scheduled_at),archivedAt:row.archived_at===null?null:String(row.archived_at)})));}
