export interface ProjectSeedOptions{seed:number;projectCount:number;tasksPerProject:number}
const BASE=Date.parse('2026-09-18T08:00:00.000Z');
function check(value:number,name:string,min:number,max:number){if(!Number.isSafeInteger(value)||value<min||value>max)throw new RangeError(`${name} must be ${min}..${max}`);}
function randomSource(seed:number){let state=seed>>>0;if(!state)state=0x9e3779b9;return()=>{state^=state<<13;state^=state>>>17;state^=state<<5;state>>>=0;return state/0x1_0000_0000;};}
function code(prefix:string,index:number){return`${prefix}-${String(index+1).padStart(4,'0')}`;}
function frozen<T extends object>(rows:T[]){return Object.freeze(rows.map(row=>Object.freeze(row)));}
export function generateProjectSeed(options:ProjectSeedOptions){check(options.seed,'seed',0,0xffff_ffff);check(options.projectCount,'projectCount',4,50);check(options.tasksPerProject,'tasksPerProject',3,100);const random=randomSource(options.seed),projects:any[]=[],milestones:any[]=[],tasks:any[]=[],risks:any[]=[],deliverables:any[]=[],events:any[]=[];let taskIndex=0,deliveryIndex=0,eventIndex=0;
for(let i=0;i<options.projectCount;i++){const projectCode=code('PRJ',i),milestoneCode=code('MS',i),kind=i%4,projectStatus=['planning','active','pending_close','closed'][kind]!,managerId=`project-manager-${String(i%4+1).padStart(2,'0')}`,stamp=new Date(BASE+i*86_400_000).toISOString();const projectTasks:any[]=[];
for(let j=0;j<options.tasksPerProject;j++){let status:string;if(kind===0)status='pending';else if(kind===1)status=['pending','in_progress','pending_review','completed','cancelled'][j%5]!;else status=j%5===4?'cancelled':'completed';const weight=10+Math.floor(random()*91),required=status!=='cancelled';const taskCode=code('TASK',taskIndex++);const completed=status==='completed'?stamp:null,cancelled=status==='cancelled'?stamp:null,submitted=status==='pending_review'?stamp:null;const row={code:taskCode,project_code:projectCode,milestone_code:milestoneCode,title:`项目任务-${i+1}-${j+1}`,description:'合成项目执行任务',assignee_id:`project-member-${String(j%6+1).padStart(2,'0')}`,weight,required,status,progress_note:status==='in_progress'?'正在执行':null,submitted_at:submitted,completed_at:completed,cancelled_at:cancelled};tasks.push(row);projectTasks.push(row);events.push({code:code('PEVT',eventIndex++),project_code:projectCode,subject_type:'task',subject_code:taskCode,event_type:'task_created',from_status:null,to_status:'pending',actor_id:managerId,comment:null,occurred_at:stamp});if(status==='completed'||status==='cancelled')events.push({code:code('PEVT',eventIndex++),project_code:projectCode,subject_type:'task',subject_code:taskCode,event_type:status==='completed'?'task_completed':'task_cancelled',from_status:'in_progress',to_status:status,actor_id:status==='completed'?managerId:'project-manager-01',comment:'合成状态事件',occurred_at:new Date(Date.parse(stamp)+60_000).toISOString()});}
const effective=projectTasks.filter(row=>row.status!=='cancelled'),total=effective.reduce((sum,row)=>sum+row.weight,0),completed=effective.filter(row=>row.status==='completed').reduce((sum,row)=>sum+row.weight,0),progress=total===0?0:Math.round(completed/total*10_000)/100,closing=kind>=2;
projects.push({code:projectCode,name:`项目-${i+1}`,manager_id:managerId,status:projectStatus,planned_start_at:'2026-09-01',planned_end_at:'2027-03-31',progress,close_requested_by:closing?managerId:null,close_requested_at:closing?stamp:null,closed_by:kind===3?'project-reviewer-01':null,closed_at:kind===3?stamp:null});milestones.push({code:milestoneCode,project_code:projectCode,name:`里程碑-${i+1}`,due_at:'2026-12-31',status:closing?'completed':'pending',completed_by:closing?managerId:null,completed_at:closing?stamp:null});const level=['low','medium','high'][i%3]!,riskStatus=kind===0?'open':kind===1?'mitigated':'closed';risks.push({code:code('RISK',i),project_code:projectCode,title:`项目风险-${i+1}`,description:'合成项目风险',level,status:riskStatus,disposition:kind===0?null:'已制定处置措施',reported_by:'project-member-01',closed_by:closing?'project-reviewer-01':null,closed_at:closing?stamp:null});const deliveryKey='project_report';deliverables.push({code:code('DEL',deliveryIndex++),project_code:projectCode,milestone_code:milestoneCode,deliverable_key:deliveryKey,name:'项目报告',business_version:'1.0',required:true,file_name:`report-${i+1}-v1.pdf`,file_digest:`sha256:project-${options.seed}-${i}-v1`,status:'rejected',submitted_by:'project-member-01',submitted_at:stamp,reviewed_by:managerId,reviewed_at:stamp,review_comment:'补充内容'});deliverables.push({code:code('DEL',deliveryIndex++),project_code:projectCode,milestone_code:milestoneCode,deliverable_key:deliveryKey,name:'项目报告',business_version:'1.1',required:true,file_name:`report-${i+1}-v2.pdf`,file_digest:`sha256:project-${options.seed}-${i}-v2`,status:closing?'accepted':'submitted',submitted_by:'project-member-01',submitted_at:stamp,reviewed_by:closing?managerId:null,reviewed_at:closing?stamp:null,review_comment:closing?'验收通过':null});events.push({code:code('PEVT',eventIndex++),project_code:projectCode,subject_type:'project',subject_code:projectCode,event_type:kind===0?'project_created':'project_activated',from_status:kind===0?null:'planning',to_status:kind===0?'planning':'active',actor_id:managerId,comment:null,occurred_at:stamp});if(closing)events.push({code:code('PEVT',eventIndex++),project_code:projectCode,subject_type:'project',subject_code:projectCode,event_type:'project_close_requested',from_status:'active',to_status:'pending_close',actor_id:managerId,comment:'合成关闭申请',occurred_at:new Date(Date.parse(stamp)+120_000).toISOString()});if(kind===3)events.push({code:code('PEVT',eventIndex++),project_code:projectCode,subject_type:'project',subject_code:projectCode,event_type:'project_closed',from_status:'pending_close',to_status:'closed',actor_id:'project-reviewer-01',comment:'合成关闭复核',occurred_at:new Date(Date.parse(stamp)+180_000).toISOString()});}
return Object.freeze({records:Object.freeze({project:frozen(projects),milestone:frozen(milestones),project_task:frozen(tasks),project_risk:frozen(risks),deliverable:frozen(deliverables),project_event:frozen(events)})});}
export const projectSeedDescriptor=Object.freeze({id:'project_task',version:'1.0.0'});
