const dashboardPresentation=Object.freeze({groups:Object.freeze([
 Object.freeze({id:'application_status',label:'申请状态',kind:'status',items:Object.freeze([
  Object.freeze({id:'draft',sourceKey:'draft',label:'草稿',tone:'neutral',moduleId:'applications'}),Object.freeze({id:'approving',sourceKey:'approving',label:'审批中',tone:'teal',moduleId:'applications'}),Object.freeze({id:'approved',sourceKey:'approved',label:'已通过',tone:'teal',moduleId:'applications'}),Object.freeze({id:'archived',sourceKey:'archived',label:'已归档',tone:'neutral',moduleId:'applications'})
 ])}),
 Object.freeze({id:'application_attention',label:'需要关注',kind:'attention',items:Object.freeze([
  Object.freeze({id:'pending_my_approvals',sourceKey:'pendingMyApprovals',label:'待我审批',tone:'amber',moduleId:'approval_nodes'}),Object.freeze({id:'upcoming_certificates',sourceKey:'upcomingCertificates',label:'即将到期证照',tone:'amber',moduleId:'certificates'}),Object.freeze({id:'expired_certificates',sourceKey:'expiredCertificates',label:'已过期证照',tone:'red',moduleId:'certificates'}),Object.freeze({id:'pending_reminders',sourceKey:'pendingReminders',label:'待处理提醒',tone:'amber',moduleId:'expiry_reminders'}),Object.freeze({id:'staged_files',sourceKey:'stagedFiles',label:'待完成文件',tone:'amber',moduleId:'file_versions'}),Object.freeze({id:'failed_files',sourceKey:'failedFiles',label:'失败文件',tone:'red',moduleId:'file_versions'})
 ])})
])});
const extensions=Object.freeze([Object.freeze({id:'application.nodes.tab',slot:'entity.detail.tabs',entityId:'application',label:'审批节点',order:20,viewId:'application_nodes'}),Object.freeze({id:'application.records.tab',slot:'entity.detail.tabs',entityId:'application',label:'审批记录',order:30,viewId:'application_records'}),Object.freeze({id:'application.files.tab',slot:'entity.detail.tabs',entityId:'application',label:'附件版本',order:40,viewId:'application_files'}),Object.freeze({id:'certificate.versions.tab',slot:'entity.detail.tabs',entityId:'certificate',label:'证照版本',order:20,viewId:'certificate_versions'}),Object.freeze({id:'certificate.reminders.tab',slot:'entity.detail.tabs',entityId:'certificate',label:'到期提醒',order:30,viewId:'certificate_reminders'}),Object.freeze({id:'certificate.files.tab',slot:'entity.detail.tabs',entityId:'certificate',label:'证照文件',order:40,viewId:'certificate_files'}),Object.freeze({id:'application.module.actions',slot:'entity.module.actions',entityId:'application',label:'申请操作',order:10,actionIds:Object.freeze(['application.create'])}),Object.freeze({id:'certificate.module.actions',slot:'entity.module.actions',entityId:'certificate',label:'证照操作',order:10,actionIds:Object.freeze(['application.certificate.create','application.certificate.refresh_reminders'])}),Object.freeze({id:'application.lifecycle.actions',slot:'entity.detail.actions',entityId:'application',label:'申请操作',order:10,actionIds:Object.freeze(['application.update','application.submit','application.approve','application.reject','application.withdraw','application.revise','application.archive'])}),Object.freeze({id:'application.file.actions',slot:'entity.detail.actions',entityId:'file_version',label:'文件操作',order:10,actionIds:Object.freeze(['application.file.finalize','application.file.recover'])}),Object.freeze({id:'application.certificate.actions',slot:'entity.detail.actions',entityId:'certificate',label:'证照操作',order:10,actionIds:Object.freeze(['application.certificate.renew'])}),Object.freeze({id:'application.reminder.actions',slot:'entity.detail.actions',entityId:'expiry_reminder',label:'提醒操作',order:10,actionIds:Object.freeze(['application.reminder.acknowledge'])}),Object.freeze({id:'application.dashboard',slot:'dashboard.sections',label:'申请归档概览',order:20,viewId:'application_dashboard',dataSource:'application.dashboard_summary',presentation:dashboardPresentation})]);
export const applicationUiDescriptor=Object.freeze({id:'application_archive',version:'1.0.0',slots:Object.freeze(['entity.detail.tabs','entity.module.actions','entity.detail.actions','dashboard.sections']as const),extensions});
