import test from 'node:test'; import assert from 'node:assert/strict'; import { createHash } from 'node:crypto'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import { loadPack } from '../../src/catalog/load-pack'; import { PackRegistry } from '../../src/catalog/registry'; import { composeDomainPacks } from '../../src/composition/compose';
import { InspectionService, inspectionRuntimeDescriptor } from '../../packs/inspection_rectification/runtime/index'; import { runInspectionAcceptanceScenario } from '../../packs/inspection_rectification/tests/index';
import { AuditService } from '../../../desktop-runtime/src/core/audit-service'; import { loadRuntimeBlueprint } from '../../../desktop-runtime/src/core/blueprint-loader'; import { openDatabase } from '../../../desktop-runtime/src/core/database'; import { DashboardService } from '../../../desktop-runtime/src/core/dashboard-service'; import { EntityRepository } from '../../../desktop-runtime/src/core/entity-repository'; import { PermissionService } from '../../../desktop-runtime/src/core/permission-service'; import { PluginRegistry } from '../../../desktop-runtime/src/core/plugin-registry'; import { compileSchema } from '../../../desktop-runtime/src/core/schema-compiler'; import type { RuntimeBlueprint } from '../../../desktop-runtime/src/shared/blueprint'; import type { ActorDto } from '../../../desktop-runtime/src/shared/dto';
const actors: Record<string, ActorDto> = { planner:{userId:1,username:'planner-01',displayName:'计划岗位',roleId:'inspection_planner'}, executor:{userId:2,username:'executor-01',displayName:'执行岗位',roleId:'inspection_executor'}, reviewer:{userId:3,username:'reviewer-01',displayName:'复核岗位',roleId:'inspection_reviewer'}, admin:{userId:4,username:'admin-01',displayName:'管理岗位',roleId:'inspection_admin'} };
test('loads and runs production inspection acceptance', (t) => {
  const pack=new PackRegistry(); pack.register(loadPack(path.resolve(__dirname,'..','..','packs','inspection_rectification'))); const composed=composeDomainPacks({blueprintSchemaVersion:'1.0',runtimeVersion:'1.0.0',software:{id:'inspection_acceptance',name:'巡检验收',version:'1.0.0',purpose:'验收巡检闭环',targetUsers:['巡检岗位'],boundaries:['离线运行'],loginMode:'required'},selections:[{id:'inspection_rectification',version:'1.0.0',config:{}}],coverage:{supported:['巡检'],unsupported:[]},materials:{developmentPurpose:'验收',industry:'运维',technicalFeatures:['离线']}},pack); assert.equal(composed.canGenerate,true,composed.summary);
  const source=JSON.stringify(composed.blueprint); const plugins=new PluginRegistry(); plugins.register(inspectionRuntimeDescriptor); const blueprint=loadRuntimeBlueprint(source,createHash('sha256').update(source).digest('hex'),plugins) as RuntimeBlueprint;
  const contributions:string[]=[]; const sink={register:(p:string,id:string)=>contributions.push(`${p}:${id}`)}; plugins.activate(blueprint.plugins,{migrations:sink,services:sink,ipc:sink,uiExtensions:sink,acceptanceScenarios:sink}); assert.ok(contributions.includes('inspection_rectification:inspection.lifecycle.acceptance'));
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'inspection-accept-')); const schema=compileSchema(blueprint); const database=openDatabase({filename:path.join(dir,'db.sqlite')}); database.migrate(schema); t.after(()=>{database.close();fs.rmSync(dir,{recursive:true,force:true});}); const repository=new EntityRepository(database,blueprint,schema); const permissions=new PermissionService(blueprint); const audit=new AuditService('1.0.0',()=>new Date('2026-09-18T08:00:00.000Z')); let n=0;
  const result=runInspectionAcceptanceScenario({database,repository,service:new InspectionService(),dashboard:new DashboardService(database,blueprint,schema),actors,context:(connection,actor)=>({connection,actor,requirePermission:(a,p)=>permissions.require(a,p),appendAudit:(c,e)=>audit.append(c,e),identityHasRole:(id,role)=>Object.values(actors).some(a=>a.username===id&&a.roleId===role),archiveBlockers:[],now:()=>new Date('2026-09-18T08:00:00.000Z'),planCode:()=>`P-${++n}`,taskCode:()=>`T-${++n}`,itemCode:()=>`I-${++n}`,eventCode:()=>`E-${++n}`})});
  assert.deepEqual(result,{status:'archived',version:9,eventCount:9,auditCount:10,total:2,abnormal:0});
});
