import test from 'node:test'; import assert from 'node:assert/strict'; import { AppError } from '../../../desktop-runtime/src/shared/errors'; import { InventoryService } from '../../packs/inventory_batch/runtime/inventory-service'; import { admin,createInventoryRuntime,inventoryContext,keeper } from '../helpers/inventory-runtime';
function configured(t:test.TestContext){const x=createInventoryRuntime(t),s=new InventoryService();const material=x.database.transaction(c=>s.createMaterial({name:'过滤器',unit:'件',expiryWarningDays:30,active:true},inventoryContext(c,admin)));const warehouse=x.database.transaction(c=>s.createWarehouse({name:'主仓库',active:true},inventoryContext(c,admin)));return{...x,s,material,warehouse};}
const input={materialCode:'',warehouseCode:'',batchNo:'LOT-001',quantity:10.125,producedAt:'2026-01-01',receivedAt:'2026-01-02',expiresAt:'2027-01-01',reason:'采购入库'};
test('receives new and existing batches with balance, ledger and audit',t=>{const x=configured(t);const req={...input,materialCode:x.material.materialCode,warehouseCode:x.warehouse.warehouseCode};const first=x.database.transaction(c=>x.s.receiveNewBatch(req,inventoryContext(c,keeper)));assert.equal(first.quantity,10.125);assert.equal(first.version,1);const second=x.database.transaction(c=>x.s.receiveExistingBatch({batchId:first.batchId,expectedVersion:1,quantity:2.5,reason:'补充入库'},inventoryContext(c,keeper)));assert.equal(second.quantity,12.625);assert.equal(second.version,2);const rows=x.database.prepare('SELECT transaction_type,quantity FROM biz_inventory_transaction WHERE batch_code=? ORDER BY id').all(first.batchCode) as Array<Record<string,unknown>>;assert.deepEqual(rows.map(r=>({...r})),[{transaction_type:'receipt',quantity:10.125},{transaction_type:'receipt',quantity:2.5}]);});
test('rejects duplicate batches, invalid dates, quantities and stale versions',t=>{const x=configured(t);const req={...input,materialCode:x.material.materialCode,warehouseCode:x.warehouse.warehouseCode};const batch=x.database.transaction(c=>x.s.receiveNewBatch(req,inventoryContext(c,keeper)));assert.throws(()=>x.database.transaction(c=>x.s.receiveNewBatch(req,inventoryContext(c,keeper))),code('UNIQUE_CONFLICT'));for(const bad of [{...req,quantity:0},{...req,quantity:1.2345},{...req,producedAt:'2026-02-01',receivedAt:'2026-01-02'},{...req,expiresAt:'2025-01-01'}])assert.throws(()=>x.database.transaction(c=>x.s.receiveNewBatch({...bad,batchNo:`BAD-${String(bad.quantity)}`},inventoryContext(c,keeper))),code('VALIDATION_FAILED'));assert.throws(()=>x.database.transaction(c=>x.s.receiveExistingBatch({batchId:batch.batchId,expectedVersion:99,quantity:1,reason:'过期'},inventoryContext(c,keeper))),code('VERSION_CONFLICT'));});
test('rolls back batch and receipt when audit fails',t=>{const x=configured(t);const req={...input,materialCode:x.material.materialCode,warehouseCode:x.warehouse.warehouseCode};assert.throws(()=>x.database.transaction(c=>x.s.receiveNewBatch(req,inventoryContext(c,keeper,{appendAudit:()=>{throw new Error('receipt audit failed');}}))),/receipt audit failed/);const row=x.database.prepare('SELECT (SELECT COUNT(*) FROM biz_inventory_batch) AS batches,(SELECT COUNT(*) FROM biz_inventory_transaction) AS transactions').get() as Record<string,number>;assert.deepEqual({...row},{batches:0,transactions:0});});
function code(expected:string){return(error:unknown)=>error instanceof AppError&&error.code===expected;}

test('rejects impossible calendar dates',t=>{const x=configured(t);const req={...input,materialCode:x.material.materialCode,warehouseCode:x.warehouse.warehouseCode,producedAt:'2026-02-30',receivedAt:'2026-03-02',batchNo:'BAD-DATE'};assert.throws(()=>x.database.transaction(c=>x.s.receiveNewBatch(req,inventoryContext(c,keeper))),code('VALIDATION_FAILED'));});

test('blocks later transactions when referenced configuration is inactive',t=>{const x=configured(t);const req={...input,materialCode:x.material.materialCode,warehouseCode:x.warehouse.warehouseCode};const batch=x.database.transaction(c=>x.s.receiveNewBatch(req,inventoryContext(c,keeper)));x.database.prepare('UPDATE biz_material SET active=0 WHERE code=?').run(x.material.materialCode);assert.throws(()=>x.database.transaction(c=>x.s.receiveExistingBatch({batchId:batch.batchId,expectedVersion:1,quantity:1,reason:'补充'},inventoryContext(c,keeper))),code('INVALID_TRANSITION'));assert.throws(()=>x.database.transaction(c=>x.s.issueStock({batchId:batch.batchId,expectedVersion:1,quantity:1,reason:'领用'},inventoryContext(c,{userId:22,username:'requester-01',displayName:'领用岗位',roleId:'inventory_requester'}))),code('INVALID_TRANSITION'));x.database.prepare('UPDATE biz_material SET active=1').run();x.database.prepare('UPDATE biz_warehouse SET active=0 WHERE code=?').run(x.warehouse.warehouseCode);assert.throws(()=>x.database.transaction(c=>x.s.adjustStock({batchId:batch.batchId,expectedVersion:1,direction:'in',quantity:1,reason:'调整'},inventoryContext(c,keeper))),code('INVALID_TRANSITION'));});
