import test from 'node:test';import assert from 'node:assert/strict';import{AppError}from'../../../desktop-runtime/src/shared/errors';import{InventoryService}from'../../packs/inventory_batch/runtime/inventory-service';import{admin,createInventoryRuntime,inventoryContext,keeper,requester}from'../helpers/inventory-runtime';
function stocked(t:test.TestContext){const x=createInventoryRuntime(t),s=new InventoryService();const m=x.database.transaction(c=>s.createMaterial({name:'物料',unit:'件',expiryWarningDays:30,active:true},inventoryContext(c,admin)));const w=x.database.transaction(c=>s.createWarehouse({name:'仓库',active:true},inventoryContext(c,admin)));const b=x.database.transaction(c=>s.receiveNewBatch({materialCode:m.materialCode,warehouseCode:w.warehouseCode,batchNo:'LOT',quantity:10,producedAt:null,receivedAt:'2026-01-01',expiresAt:'2027-01-01',reason:'入库'},inventoryContext(c,keeper)));return{...x,s,b};}
test('issues, returns and adjusts stock with immutable ledger',t=>{const x=stocked(t);const issue=x.database.transaction(c=>x.s.issueStock({batchId:x.b.batchId,expectedVersion:1,quantity:4,reason:'领用'},inventoryContext(c,requester)));assert.equal(issue.quantity,6);const returned=x.database.transaction(c=>x.s.returnStock({issueTransactionId:issue.transactionId,batchId:x.b.batchId,expectedVersion:2,quantity:2,reason:'退回'},inventoryContext(c,requester)));assert.equal(returned.quantity,8);assert.throws(()=>x.database.transaction(c=>x.s.returnStock({issueTransactionId:issue.transactionId,batchId:x.b.batchId,expectedVersion:3,quantity:3,reason:'超额'},inventoryContext(c,requester))),code('VALIDATION_FAILED'));let adjusted=x.database.transaction(c=>x.s.adjustStock({batchId:x.b.batchId,expectedVersion:3,direction:'out',quantity:3,reason:'盘亏'},inventoryContext(c,keeper)));assert.equal(adjusted.quantity,5);adjusted=x.database.transaction(c=>x.s.adjustStock({batchId:x.b.batchId,expectedVersion:4,direction:'in',quantity:1,reason:'盘盈'},inventoryContext(c,keeper)));assert.equal(adjusted.quantity,6);const issueRow=x.database.prepare('SELECT quantity FROM biz_inventory_transaction WHERE id=?').get(issue.transactionId) as {quantity:number};assert.equal(issueRow.quantity,4);});
test('rejects negative stock, wrong source and rolls back audit failure',t=>{const x=stocked(t);assert.throws(()=>x.database.transaction(c=>x.s.issueStock({batchId:x.b.batchId,expectedVersion:1,quantity:11,reason:'超额'},inventoryContext(c,requester))),code('VALIDATION_FAILED'));assert.throws(()=>x.database.transaction(c=>x.s.returnStock({issueTransactionId:999,batchId:x.b.batchId,expectedVersion:1,quantity:1,reason:'错误'},inventoryContext(c,requester))),code('NOT_FOUND'));assert.throws(()=>x.database.transaction(c=>x.s.adjustStock({batchId:x.b.batchId,expectedVersion:1,direction:'out',quantity:11,reason:'盘亏'},inventoryContext(c,keeper))),code('VALIDATION_FAILED'));assert.throws(()=>x.database.transaction(c=>x.s.issueStock({batchId:x.b.batchId,expectedVersion:1,quantity:1,reason:'领用'},inventoryContext(c,requester,{appendAudit:()=>{throw new Error('issue audit failed');}}))),/issue audit failed/);const batch=x.database.prepare('SELECT quantity,version FROM biz_inventory_batch WHERE id=?').get(x.b.batchId) as Record<string,unknown>;assert.deepEqual({...batch},{quantity:10,version:1});});
function code(expected:string){return(error:unknown)=>error instanceof AppError&&error.code===expected;}

test('allows only the original requester to return an issue',t=>{const x=stocked(t);const issue=x.database.transaction(c=>x.s.issueStock({batchId:x.b.batchId,expectedVersion:1,quantity:2,reason:'本人领用'},inventoryContext(c,requester)));assert.throws(()=>x.database.transaction(c=>x.s.returnStock({issueTransactionId:issue.transactionId,batchId:x.b.batchId,expectedVersion:2,quantity:1,reason:'他人退库'},inventoryContext(c,{...requester,username:'requester-02'}))),code('PERMISSION_DENIED'));});

test('runs read-only issue blockers before changing inventory',t=>{const x=stocked(t);let calls=0;const blocker=(_request:any,read:any)=>{calls+=1;const safe=typeof read.prepare!=='function'&&read.find('inventory_batch',{id:x.b.batchId}).length===1;return{blocked:safe,code:'APPROVAL_REQUIRED',message:'申领尚未批准'};};assert.throws(()=>x.database.transaction(c=>x.s.issueStock({batchId:x.b.batchId,expectedVersion:1,quantity:1,reason:'待审批领用'},inventoryContext(c,requester,{issueBlockers:[blocker]}))),code('INVALID_TRANSITION'));assert.equal(calls,1);const row=x.database.prepare('SELECT quantity,version FROM biz_inventory_batch WHERE id=?').get(x.b.batchId)as Record<string,unknown>;assert.deepEqual({...row},{quantity:10,version:1});});

test('normalizes decimal balances and ledger amounts and rejects overflow',t=>{const x=stocked(t);x.database.prepare('UPDATE biz_inventory_batch SET quantity=0.3 WHERE id=?').run(x.b.batchId);const issued=x.database.transaction(c=>x.s.issueStock({batchId:x.b.batchId,expectedVersion:1,quantity:0.100000000001,reason:'小数领用'},inventoryContext(c,requester)));assert.equal(issued.quantity,0.2);const ledger=x.database.prepare('SELECT quantity FROM biz_inventory_transaction WHERE id=?').get(issued.transactionId)as{quantity:number};assert.equal(ledger.quantity,0.1);x.database.prepare('UPDATE biz_inventory_batch SET quantity=? WHERE id=?').run(Number.MAX_VALUE,x.b.batchId);assert.throws(()=>x.database.transaction(c=>x.s.adjustStock({batchId:x.b.batchId,expectedVersion:2,direction:'in',quantity:Number.MAX_VALUE,reason:'溢出'},inventoryContext(c,{...keeper,roleId:'inventory_reviewer'}))),code('VALIDATION_FAILED'));});

test('blocks returns after the referenced warehouse is disabled',t=>{const x=stocked(t);const issue=x.database.transaction(c=>x.s.issueStock({batchId:x.b.batchId,expectedVersion:1,quantity:1,reason:'领用'},inventoryContext(c,requester)));x.database.prepare('UPDATE biz_warehouse SET active=0').run();assert.throws(()=>x.database.transaction(c=>x.s.returnStock({issueTransactionId:issue.transactionId,batchId:x.b.batchId,expectedVersion:2,quantity:1,reason:'退库'},inventoryContext(c,requester))),code('INVALID_TRANSITION'));});
