import assert from 'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import test from'node:test';
import{compileSchema}from'../../../desktop-runtime/src/core/schema-compiler';import{openDatabase}from'../../../desktop-runtime/src/core/database';import{linkReadyDeliveryArchive,createRequiredArchiveCloseBlocker,type ProjectArchiveContext}from'../../packs/project_archive_bridge/runtime/project-archive';import type{ProjectReadConnection}from'../../packs/project_task/runtime/types';import{loadPack}from'../../src/catalog/load-pack';import{PackRegistry}from'../../src/catalog/registry';import{composeDomainPacks}from'../../src/composition/compose';
const actor=Object.freeze({userId:1,username:'archive-manager',displayName:'归档管理员',roleId:'application_archive_manager'});
function composeBridge(){const registry=new PackRegistry();for(const id of['project_task','application_archive','project_archive_bridge'])registry.register(loadPack(path.resolve(__dirname,'..','..','packs',id)));return composeDomainPacks({blueprintSchemaVersion:'1.0',runtimeVersion:'1.0.0',software:{id:'project_archive_test',name:'项目归档测试',version:'1.0.0',purpose:'验证交付归档',targetUsers:['项目人员'],boundaries:['离线'],loginMode:'required'},selections:[{id:'project_task',version:'1.0.0',config:{}},{id:'application_archive',version:'1.0.0',config:{}},{id:'project_archive_bridge',version:'1.0.0',config:{}}],coverage:{supported:['交付归档'],unsupported:[]},materials:{developmentPurpose:'验证交付归档',industry:'项目管理',technicalFeatures:['不可变关联']}},registry);}
function setup(t:test.TestContext){const composed=composeBridge();assert.equal(composed.canGenerate,true,composed.summary);const dir=fs.mkdtempSync(path.join(os.tmpdir(),'project-archive-')),schema=compileSchema(composed.blueprint as any),database=openDatabase({filename:path.join(dir,'db.sqlite')});database.migrate(schema);const now='2026-09-20T08:00:00.000Z';database.prepare("INSERT INTO biz_project(code,name,manager_id,status,planned_start_at,planned_end_at,progress,close_requested_by,close_requested_at,closed_by,closed_at,version,created_at,updated_at) VALUES('PRJ-1','交付项目','manager','active','2026-01-01','2026-12-31',100,NULL,NULL,NULL,NULL,1,?,?)").run(now,now);database.prepare("INSERT INTO biz_deliverable(code,project_code,milestone_code,deliverable_key,name,business_version,required,file_name,file_digest,status,submitted_by,submitted_at,reviewed_by,reviewed_at,review_comment,version,created_at,updated_at) VALUES('DEL-1','PRJ-1',NULL,'manual','用户手册','1.0',1,'manual.pdf','abc','accepted','member',?,'reviewer',?,'通过',2,?,?)").run(now,now,now,now);for(const[file,status]of[['FILE-READY','ready'],['FILE-STAGED','staged']]as const)database.prepare("INSERT INTO biz_file_version(code,owner_type,owner_code,business_key,business_version,original_name,relative_path,sha256,size_bytes,storage_status,stage_token,submitted_by,staged_at,ready_at,failure_reason,version,created_at,updated_at) VALUES(?,'domain_document','PRJ-1','manual','1.0','manual.pdf',?, ?,10,?,NULL,'archive-manager',?,?,NULL,1,?,?)").run(file,`files/${file}.bin`,'0'.repeat(64),status,now,status==='ready'?now:null,now,now);t.after(()=>{database.close();fs.rmSync(dir,{recursive:true,force:true});});return{database};}
function context(connection:any):ProjectArchiveContext{return{connection,actor,requirePermission:()=>undefined,now:()=>new Date('2026-09-20T08:00:00.000Z')};}
function reader(connection:any):ProjectReadConnection{return{find:(entity,filters)=>{const entries=Object.entries(filters),where=entries.map(([k])=>`${k}=?`).join(' AND ');return connection.prepare(`SELECT * FROM biz_${entity} WHERE ${where}`).all(...entries.map(([,v])=>v))as any[];}};}
test('composes immutable delivery archive links and bidirectional tabs',()=>{const result=composeBridge();assert.equal(result.canGenerate,true,result.summary);const entities=result.blueprint!.entities as any[];assert.equal(entities.find(x=>x.id==='project_delivery_archive').retention,'append_only');assert.ok(entities.find(x=>x.id==='project').detailTabs.some((x:any)=>x.id==='delivery_archives'));assert.ok(entities.find(x=>x.id==='file_version').detailTabs.some((x:any)=>x.id==='project_delivery'));});
test('links accepted delivery to ready file idempotently and rejects conflicting or staged files',t=>{const x=setup(t);const first=x.database.transaction(c=>linkReadyDeliveryArchive({projectId:1,deliverableId:1,fileVersionCode:'FILE-READY'},context(c)));const same=x.database.transaction(c=>linkReadyDeliveryArchive({projectId:1,deliverableId:1,fileVersionCode:'FILE-READY'},context(c)));assert.equal(same.archiveCode,first.archiveCode);assert.throws(()=>x.database.transaction(c=>linkReadyDeliveryArchive({projectId:1,deliverableId:1,fileVersionCode:'FILE-STAGED'},context(c))),/conflict|ready/i);assert.equal((x.database.prepare('SELECT COUNT(*) count FROM biz_project_delivery_archive').get()as{count:number}).count,1);});
test('blocks project close until every latest required delivery is archived',t=>{const x=setup(t),blocker=createRequiredArchiveCloseBlocker();x.database.transaction(c=>{assert.equal(blocker(1,reader(c)).blocked,true);linkReadyDeliveryArchive({projectId:1,deliverableId:1,fileVersionCode:'FILE-READY'},context(c));assert.equal(blocker(1,reader(c)).blocked,false);});});
