. "$PSScriptRoot\Assert.ps1"
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot '..\lib\StandardDocumentQuality.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot '..\lib\StandardSourceMaterial.psm1') -Force -DisableNameChecking
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.Drawing

function Add-ZipText($Archive,[string]$Name,[string]$Text){$entry=$Archive.CreateEntry($Name);$writer=[IO.StreamWriter]::new($entry.Open(),[Text.UTF8Encoding]::new($false));try{$writer.Write($Text)}finally{$writer.Dispose()}}
function Escape-Xml([string]$Value){return [Security.SecurityElement]::Escape($Value)}
function New-TestDocx([string]$Path,[int]$Pages,[string]$Text,[int]$Tables=0,[string[]]$Images=@(),[string[]]$Bookmarks=@(),[hashtable]$Variables=@{},[string[]]$Headings=@(),[string[]]$TableLabels=@(),[string[]]$NumberedItems=@(),[object[]]$SectionTables=@(),[string[]]$WorkflowItems=@(),[string]$WorkflowProse='',[object[]]$PageGroups=@(),[string]$HeaderText='',[int]$ActualPages=$Pages){
    if(Test-Path -LiteralPath $Path){Remove-Item -LiteralPath $Path -Force};$parent=Split-Path -Parent $Path;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$archive=[IO.Compression.ZipFile]::Open($Path,[IO.Compression.ZipArchiveMode]::Create)
    try{
        $paragraphs=[Text.StringBuilder]::new();foreach($heading in $Headings){[void]$paragraphs.Append('<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:rPr><w:sz w:val="8"/></w:rPr><w:t>').Append((Escape-Xml $heading)).Append('</w:t></w:r></w:p>')};$offset=0;while($offset-lt$Text.Length){$count=[Math]::Min(240,$Text.Length-$offset);[void]$paragraphs.Append('<w:p><w:r><w:rPr><w:sz w:val="8"/></w:rPr><w:t xml:space="preserve">').Append((Escape-Xml $Text.Substring($offset,$count))).Append('</w:t></w:r></w:p>');$offset+=$count};if($Text.Length-eq0){[void]$paragraphs.Append('<w:p/>')};foreach($item in $NumberedItems){[void]$paragraphs.Append('<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:rPr><w:sz w:val="8"/></w:rPr><w:t>').Append((Escape-Xml $item)).Append('</w:t></w:r></w:p>')}
        $bookmarkId=1;foreach($bookmark in $Bookmarks){[void]$paragraphs.Append('<w:p><w:bookmarkStart w:id="').Append($bookmarkId).Append('" w:name="').Append((Escape-Xml $bookmark)).Append('"/><w:r><w:t>占位</w:t></w:r><w:bookmarkEnd w:id="').Append($bookmarkId).Append('"/></w:p>');$bookmarkId++}
        1..$Tables|ForEach-Object{if($Tables-gt0){$label=if($_-le$TableLabels.Count){$TableLabels[$_-1]}else{'质量表格'+$_};[void]$paragraphs.Append('<w:tbl><w:tr><w:tc><w:p><w:r><w:t>').Append((Escape-Xml $label)).Append('</w:t></w:r></w:p></w:tc></w:tr></w:tbl>')}};foreach($sectionTable in $SectionTables){[void]$paragraphs.Append('<w:p><w:pPr><w:pStyle w:val="Heading2"/></w:pPr><w:r><w:rPr><w:sz w:val="8"/></w:rPr><w:t>').Append((Escape-Xml ([string]$sectionTable.heading))).Append('</w:t></w:r></w:p><w:tbl><w:tr><w:tc><w:p><w:r><w:t>').Append((Escape-Xml ([string]$sectionTable.text))).Append('</w:t></w:r></w:p></w:tc></w:tr></w:tbl>')};if($WorkflowItems.Count-or-not[string]::IsNullOrWhiteSpace($WorkflowProse)){[void]$paragraphs.Append('<w:p><w:pPr><w:pStyle w:val="Heading2"/></w:pPr><w:r><w:t>完整业务流程</w:t></w:r></w:p>');if(-not[string]::IsNullOrWhiteSpace($WorkflowProse)){[void]$paragraphs.Append('<w:p><w:r><w:t>').Append((Escape-Xml $WorkflowProse)).Append('</w:t></w:r></w:p>')};foreach($item in $WorkflowItems){[void]$paragraphs.Append('<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>').Append((Escape-Xml $item)).Append('</w:t></w:r></w:p>')}}
        $rels=[Text.StringBuilder]::new('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">');$imageIndex=0;foreach($image in $Images){$imageIndex++;$name='image'+$imageIndex+'.png';$entry=$archive.CreateEntry('word/media/'+$name);$input=[IO.File]::OpenRead($image);$output=$entry.Open();try{$input.CopyTo($output)}finally{$output.Dispose();$input.Dispose()};[void]$rels.Append('<Relationship Id="rIdImage').Append($imageIndex).Append('" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/').Append($name).Append('"/>');[void]$paragraphs.Append('<w:p><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="9144" cy="6858"/><wp:docPr id="').Append($imageIndex).Append('" name="Picture ').Append($imageIndex).Append('"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="').Append($imageIndex).Append('" name="').Append($name).Append('"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rIdImage').Append($imageIndex).Append('"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="9144" cy="6858"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>')};[void]$rels.Append('</Relationships>')
        if($PageGroups.Count){[void]$paragraphs.Clear();$pageNumber=0;foreach($group in $PageGroups){$pageNumber++;if($pageNumber-gt1){[void]$paragraphs.Append('<w:p><w:r><w:br w:type="page"/></w:r></w:p>')};foreach($line in @($group)){[void]$paragraphs.Append('<w:p><w:r><w:rPr><w:sz w:val="8"/></w:rPr><w:t xml:space="preserve">').Append((Escape-Xml ([string]$line))).Append('</w:t></w:r></w:p>')}}}else{2..$ActualPages|ForEach-Object{if($ActualPages-gt1){[void]$paragraphs.Append('<w:p><w:r><w:br w:type="page"/></w:r></w:p><w:p><w:r><w:rPr><w:sz w:val="20"/></w:rPr><w:t>质量验证页 ').Append($_).Append('</w:t></w:r></w:p>')}}};$document='<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>'+$paragraphs.ToString()+'<w:sectPr/></w:body></w:document>'
        $docVars=($Variables.GetEnumerator()|ForEach-Object{'<w:docVar w:name="'+(Escape-Xml ([string]$_.Key))+'" w:val="'+(Escape-Xml ([string]$_.Value))+'"/>'})-join'';$settings='<?xml version="1.0" encoding="UTF-8"?><w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docVars>'+$docVars+'</w:docVars></w:settings>'
        Add-ZipText $archive '[Content_Types].xml' '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>'
        Add-ZipText $archive '_rels/.rels' '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>'
        $rels.Insert($rels.Length-16,'<Relationship Id="rIdSettings" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>')|Out-Null
        Add-ZipText $archive 'word/document.xml' $document;Add-ZipText $archive 'word/_rels/document.xml.rels' $rels.ToString();Add-ZipText $archive 'word/settings.xml' $settings;if(-not[string]::IsNullOrWhiteSpace($HeaderText)){Add-ZipText $archive 'word/header1.xml' ('<?xml version="1.0" encoding="UTF-8"?><w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:r><w:t>'+(Escape-Xml $HeaderText)+'</w:t></w:r></w:p></w:hdr>')};Add-ZipText $archive 'docProps/app.xml' ('<?xml version="1.0" encoding="UTF-8"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Pages>'+$Pages+'</Pages></Properties>')
    }finally{$archive.Dispose()}
}
function New-TestPdf([string]$Path,[int]$Pages,[switch]$Blank,[switch]$Variant){$objects=[Collections.Generic.List[string]]::new();$kids=@(1..$Pages|ForEach-Object{($_+2).ToString()+' 0 R'})-join' ';$objects.Add('<< /Type /Catalog /Pages 2 0 R >>');$objects.Add('<< /Type /Pages /Kids [ '+$kids+' ] /Count '+$Pages+' >>');for($i=0;$i-lt$Pages;$i++){$objects.Add('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents '+($Pages+3)+' 0 R >>')};$content=if($Blank){''}elseif($Variant){'0 0 0 rg 72 700 240 60 re f 315 700 12 12 re f'}else{'0 0 0 rg 72 700 240 60 re f'};$objects.Add("<< /Length $($content.Length) >>`nstream`n$content`nendstream");$builder=[Text.StringBuilder]::new("%PDF-1.4`n");$offsets=[Collections.Generic.List[int]]::new();for($i=0;$i-lt$objects.Count;$i++){$offsets.Add([Text.Encoding]::ASCII.GetByteCount($builder.ToString()));[void]$builder.Append(($i+1)).Append(" 0 obj`n").Append($objects[$i]).Append("`nendobj`n")};$xref=[Text.Encoding]::ASCII.GetByteCount($builder.ToString());[void]$builder.Append('xref').Append("`n0 ").Append($objects.Count+1).Append("`n0000000000 65535 f `n");foreach($offset in $offsets){[void]$builder.Append($offset.ToString('D10')).Append(" 00000 n `n")};[void]$builder.Append('trailer').Append("`n<< /Size ").Append($objects.Count+1).Append(" /Root 1 0 R >>`nstartxref`n").Append($xref).Append("`n%%EOF`n");[IO.File]::WriteAllBytes($Path,[Text.Encoding]::ASCII.GetBytes($builder.ToString()))}
function Export-TestPdf([string]$Docx,[string]$Pdf){$inspector=Join-Path $PSScriptRoot '..\template\tools\word-page-inspector.ps1';$previous=$ErrorActionPreference;try{$ErrorActionPreference='Continue';$output=& powershell -NoProfile -ExecutionPolicy Bypass -File $inspector -DocxPath $Docx -ReferencePdfPath $Pdf 2>&1|Out-String;$exit=$LASTEXITCODE}finally{$ErrorActionPreference=$previous};if($exit-ne0){throw "Fixture PDF export failed: $output"}}
function Set-TestDocxVariable([string]$Docx,[string]$Name,[string]$Value){$archive=[IO.Compression.ZipFile]::Open($Docx,[IO.Compression.ZipArchiveMode]::Update);try{$entry=$archive.GetEntry('word/settings.xml');$reader=[IO.StreamReader]::new($entry.Open(),[Text.Encoding]::UTF8,$true);try{[xml]$xml=$reader.ReadToEnd()}finally{$reader.Dispose()};$ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main';$manager=[Xml.XmlNamespaceManager]::new($xml.NameTable);$manager.AddNamespace('w',$ns);$node=$xml.SelectSingleNode("//w:docVar[@w:name='$Name']",$manager);if($null-eq$node){$container=$xml.SelectSingleNode('//w:docVars',$manager);if($null-eq$container){$container=$xml.CreateElement('w','docVars',$ns);[void]$xml.DocumentElement.AppendChild($container)};$node=$xml.CreateElement('w','docVar',$ns);[void]$node.SetAttribute('name',$ns,$Name);[void]$container.AppendChild($node)};[void]$node.SetAttribute('val',$ns,$Value);$entry.Delete();$replacement=$archive.CreateEntry('word/settings.xml');$writer=[IO.StreamWriter]::new($replacement.Open(),[Text.UTF8Encoding]::new($false));try{$writer.Write($xml.OuterXml)}finally{$writer.Dispose()}}finally{$archive.Dispose()}}
function Add-TestAppProperty([string]$Docx,[string]$Text,[string]$Element='HyperlinkBase'){$archive=[IO.Compression.ZipFile]::Open($Docx,[IO.Compression.ZipArchiveMode]::Update);try{$entry=$archive.GetEntry('docProps/app.xml');$reader=[IO.StreamReader]::new($entry.Open(),[Text.Encoding]::UTF8,$true);try{$xml=$reader.ReadToEnd()}finally{$reader.Dispose()};$xml=$xml.Replace('</Properties>','<'+$Element+'>'+(Escape-Xml $Text)+'</'+$Element+'></Properties>');$entry.Delete();Add-ZipText $archive 'docProps/app.xml' $xml}finally{$archive.Dispose()}}
function Add-TestExternalRelationship([string]$Docx,[string]$Target){$archive=[IO.Compression.ZipFile]::Open($Docx,[IO.Compression.ZipArchiveMode]::Update);try{$entry=$archive.GetEntry('word/_rels/document.xml.rels');$reader=[IO.StreamReader]::new($entry.Open(),[Text.Encoding]::UTF8,$true);try{$xml=$reader.ReadToEnd()}finally{$reader.Dispose()};$xml=$xml.Replace('</Relationships>','<Relationship Id="rIdExternal" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="'+(Escape-Xml $Target)+'" TargetMode="External"/></Relationships>');$entry.Delete();Add-ZipText $archive 'word/_rels/document.xml.rels' $xml}finally{$archive.Dispose()}}
function Add-TestInstructionText([string]$Docx,[string]$Text){$archive=[IO.Compression.ZipFile]::Open($Docx,[IO.Compression.ZipArchiveMode]::Update);try{$entry=$archive.GetEntry('word/document.xml');$reader=[IO.StreamReader]::new($entry.Open(),[Text.Encoding]::UTF8,$true);try{$xml=$reader.ReadToEnd()}finally{$reader.Dispose()};$xml=$xml.Replace('<w:sectPr/>','<w:p><w:r><w:instrText>'+(Escape-Xml $Text)+'</w:instrText></w:r></w:p><w:sectPr/>');$entry.Delete();Add-ZipText $archive 'word/document.xml' $xml}finally{$archive.Dispose()}}
function Remove-TestDocxParagraph([string]$Docx,[string]$Text){$archive=[IO.Compression.ZipFile]::Open($Docx,[IO.Compression.ZipArchiveMode]::Update);try{$entry=$archive.GetEntry('word/document.xml');$reader=[IO.StreamReader]::new($entry.Open(),[Text.Encoding]::UTF8,$true);try{[xml]$xml=$reader.ReadToEnd()}finally{$reader.Dispose()};$ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main';$manager=[Xml.XmlNamespaceManager]::new($xml.NameTable);$manager.AddNamespace('w',$ns);$node=@($xml.SelectNodes('//w:p',$manager)|Where-Object{(@($_.SelectNodes('.//w:t',$manager)|ForEach-Object InnerText)-join'')-match[regex]::Escape($Text)}|Select-Object -First 1);if($node.Count-ne1){throw 'Paragraph fixture was not found.'};[void]$node[0].ParentNode.RemoveChild($node[0]);$entry.Delete();Add-ZipText $archive 'word/document.xml' $xml.OuterXml}finally{$archive.Dispose()}}
function New-Png([string]$Path,[int]$Index){$bitmap=[Drawing.Bitmap]::new(80,60);$g=[Drawing.Graphics]::FromImage($bitmap);try{$g.Clear([Drawing.Color]::FromArgb(255,($Index*47)%255,($Index*83)%255,($Index*113)%255));$g.DrawString([string]$Index,[Drawing.Font]::new('Arial',14),[Drawing.Brushes]::Black,8,8);$bitmap.Save($Path,[Drawing.Imaging.ImageFormat]::Png)}finally{$g.Dispose();$bitmap.Dispose()}}
function Content([string[]]$Headings,[int]$Length,[string]$Name,[string]$Version){$text=$Name+' V'+$Version+' '+($Headings-join' ')+' ';while([regex]::Matches($text.Normalize([Text.NormalizationForm]::FormKC),'[\p{L}\p{Nd}]').Count-lt$Length){$text+='业务流程数据权限状态校验处理结果说明。'};return $text}

$root=Join-Path ([IO.Path]::GetTempPath()) ('standard-quality-'+[guid]::NewGuid().ToString('N'))
try{
    $name='边缘云智能业务分发平台软件';$version='1.0.0';$facts=[pscustomobject]@{factVersion='1.0';templateId='project_task_management';software=[pscustomobject]@{name=$name;version=$version};modules=@([pscustomobject]@{id='projects';name='项目管理'},[pscustomobject]@{id='project_tasks';name='项目任务'},[pscustomobject]@{id='project_risks';name='项目风险'});entities=@([pscustomobject]@{id='project';name='项目';isCore=$true;fields=@([pscustomobject]@{id='project_code';name='项目编码'})},[pscustomobject]@{id='project_task';name='项目任务';isCore=$true;fields=@([pscustomobject]@{id='task_code';name='任务编码'})},[pscustomobject]@{id='project_risk';name='项目风险';isCore=$true;fields=@([pscustomobject]@{id='risk_code';name='风险编码'})});roles=@([pscustomobject]@{id='operations_admin';name='系统管理员'});commands=@([pscustomobject]@{id='project.create';label='创建项目';moduleId='projects'});workflows=@([pscustomobject]@{steps=@([pscustomobject]@{label='项目立项';prerequisite='项目信息完整';result='形成项目记录';failure='信息错误时拒绝'},[pscustomobject]@{label='任务执行';prerequisite='项目已经激活';result='形成任务进展';failure='状态错误时拒绝'})});source=[pscustomobject]@{sha256=('a'*64)};evidence=[pscustomobject]@{executableSha256=('b'*64);resourceManifestSha256=('c'*64);blueprintSha256=('d'*64);screenshotManifestSha256=('f'*64)};screenshots=[pscustomobject]@{captures=@()}}
    $assets=Join-Path $root 'assets';New-Item -ItemType Directory -Path $assets|Out-Null;$screenshots=@();1..12|ForEach-Object{$path=Join-Path $assets ("shot$_.png");New-Png $path $_;$screenshots+=$path;$facts.screenshots.captures+=[pscustomobject]@{imageSha256=(Get-FileHash $path -Algorithm SHA256).Hash.ToLowerInvariant()}};$diagrams=@();13..17|ForEach-Object{$path=Join-Path $assets ("diagram$_.png");New-Png $path $_;$diagrams+=$path}
    $sourceRoot=Join-Path $root 'source-root';$sourcePath=Join-Path $sourceRoot 'src\app.ts';New-Item -ItemType Directory -Path (Split-Path -Parent $sourcePath) -Force|Out-Null;$sourceLines=@(1..2940|ForEach-Object{'export const line'+$_.ToString('D4')+' = true;'});[IO.File]::WriteAllText($sourcePath,($sourceLines-join"`n"),[Text.UTF8Encoding]::new($false));$sourceHash=(Get-FileHash $sourcePath -Algorithm SHA256).Hash.ToLowerInvariant();$sourceItem=Get-Item $sourcePath;$sourceCanonical='src/app.ts|2940|'+$sourceItem.Length+'|'+$sourceHash;$sourceManifestHash=[BitConverter]::ToString(([Security.Cryptography.SHA256]::Create().ComputeHash([Text.UTF8Encoding]::new($false).GetBytes($sourceCanonical)))).Replace('-','').ToLowerInvariant();$sourceManifest=[pscustomobject]@{manifestVersion='1.0';templateId='project_task_management';totalFiles=1;totalLines=2940;sha256=$sourceManifestHash;files=@([pscustomobject]@{path='src/app.ts';lines=2940;bytes=$sourceItem.Length;sha256=$sourceHash})};$sourcePlan=Get-StandardSourcePrintPlan -RepositoryRoot $sourceRoot -SourceManifest $sourceManifest;$facts.source.sha256=$sourceManifestHash;$facts.source|Add-Member -NotePropertyName totalFiles -NotePropertyValue 1;$facts.source|Add-Member -NotePropertyName totalLines -NotePropertyValue 2940
    $baseline=Join-Path $root 'baseline';New-Item -ItemType Directory -Path $baseline|Out-Null;$bookmarks=@('category','classification','company_date','completion_date','development_hardware','development_os','development_purpose','development_tools','industry','language','main_functions','runtime_hardware','runtime_platform','runtime_support','short_name','software_name','source_quantity','technical_features','version')|ForEach-Object{'app_'+$_}
    $introHeadings=@('建设目的','适用用户','业务范围','完整业务流程','数据特征','技术架构','能力边界');New-TestDocx (Join-Path $baseline 'introduction.docx') 3 (Content ($introHeadings+@('项目管理','项目任务','项目风险')) 1300 $name $version) -Headings $introHeadings
    New-TestDocx (Join-Path $baseline 'feature-table.docx') 6 (Content @('软件功能表','项目管理','项目任务','项目风险') 2600 $name $version) -Headings @('软件功能表') -SectionTables @([pscustomobject]@{heading='项目管理';text='项目管理 创建项目'},[pscustomobject]@{heading='项目任务';text='项目任务 操作字段'},[pscustomobject]@{heading='项目风险';text='项目风险 操作字段'})
    New-TestDocx (Join-Path $baseline 'manual.docx') 15 (Content @('操作手册','完整业务流程','步骤 1','备份与恢复','项目管理','项目任务','项目风险') 3200 $name $version) -Tables 2 -Images $screenshots -Headings @('操作手册','备份与恢复') -WorkflowItems @('步骤 1 项目立项 项目信息完整 形成项目记录 信息错误时拒绝','步骤 2 任务执行 项目已经激活 形成任务进展 状态错误时拒绝')
    New-TestDocx (Join-Path $baseline 'database-design.docx') 12 (Content @('数据库设计','核心数据字典','实体关系','项目','项目任务','项目风险') 3600 $name $version) -Images @($diagrams[0]) -Headings @('数据库设计','核心数据字典','实体关系') -SectionTables @([pscustomobject]@{heading='项目';text='项目 项目编码'},[pscustomobject]@{heading='项目任务';text='项目任务 任务编码'},[pscustomobject]@{heading='项目风险';text='项目风险 风险编码'})
    New-TestDocx (Join-Path $baseline 'runtime.docx') 3 (Content @('运行环境说明','安装准备','备份与恢复') 900 $name $version) -Tables 2 -Headings @('运行环境说明','安装准备','备份与恢复')
    New-TestDocx (Join-Path $baseline 'prototype.docx') 6 (Content @('导航层级','列表、详情与表单','角色操作矩阵','业务流程','实体关系','项目','项目任务','项目风险') 1200 $name $version) -Tables 1 -Images $diagrams -Headings @('导航层级','列表、详情与表单','角色操作矩阵','业务流程','实体关系')
    $applicationText=Content @('计算机软件著作权登记申请信息','【申请人填写】','【生成时按实际源码统计填写】') 500 $name $version;New-TestDocx (Join-Path $baseline 'application-info.docx') 2 $applicationText -Tables 1 -Bookmarks $bookmarks -Headings @('计算机软件著作权登记申请信息')
    $sourceGroups=@();foreach($page in @($sourcePlan.pages)){$group=[Collections.Generic.List[string]]::new();$group.Add(('打印页 '+$page.outputPage+'/'+$sourcePlan.expectedPageCount+'　源码页 '+$page.sourcePage+'/'+$sourcePlan.totalSourcePages));foreach($mapping in @($page.mappings)){$index=[Array]::IndexOf([object[]]@($sourcePlan.selectedFiles),[object][string]$mapping.path)+1;$prefix=if($mapping.part-eq0){'F{0:D3} = '-f$index}else{'       '};$group.Add($prefix+[string]$mapping.text)};foreach($line in @($page.lines)){$index=[Array]::IndexOf([object[]]@($sourcePlan.selectedFiles),[object][string]$line.path)+1;$location=('F{0:D3}:{1}'-f$index,$line.lineNumber)+$(if($line.continuation-gt0){'.'+$line.continuation}else{''});$group.Add($location+"`t"+[string]$line.text)};$sourceGroups+=,$group.ToArray()};$sourceHtmlPath=Join-Path $baseline 'source.html';[void](Write-StandardSourceHtml -Plan $sourcePlan -SoftwareName $name -Version $version -OutputPath $sourceHtmlPath);$sourcePlanPath=Join-Path $baseline 'source-plan.json';[IO.File]::WriteAllText($sourcePlanPath,($sourcePlan|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));$sourceWork=[pscustomobject]@{HtmlPath=$sourceHtmlPath;SourcePlanPath=$sourcePlanPath;SourceHtmlSha256=(Get-FileHash $sourceHtmlPath -Algorithm SHA256).Hash.ToLowerInvariant();DocxPath=(Join-Path $baseline 'source.docx');PdfPath=(Join-Path $baseline 'source.pdf');SourceDocument=$true;ExplicitSourceDocument=$true;ExpectedSourcePages=[int]$sourcePlan.expectedPageCount;SourceManifestSha256=[string]$sourcePlan.sourceManifestSha256;SelectionSha256=[string]$sourcePlan.selectionSha256;SourceTotalFiles=[int]$sourcePlan.totalFiles;SourceTotalLogicalLines=[int]$sourcePlan.totalLogicalLines;SourceTotalPrintLines=[int]$sourcePlan.totalPrintLines;PrototypeDocument=$false;ApplicationDocument=$false;SoftwareName=$name;Version=$version};$sourceWorkPath=Join-Path $baseline 'source.work.json';[IO.File]::WriteAllText($sourceWorkPath,($sourceWork|ConvertTo-Json -Depth 5),[Text.UTF8Encoding]::new($false));$sourceWorker=Join-Path $PSScriptRoot '..\template\tools\word-export-worker.ps1';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$sourceWorkerOutput=& powershell -NoProfile -ExecutionPolicy Bypass -File $sourceWorker -ProjectRoot $repoRoot -WorkItemsPath $sourceWorkPath 2>&1|Out-String;if($LASTEXITCODE-ne0){throw "Source fixture export failed: $sourceWorkerOutput"};Remove-Item -LiteralPath $sourceHtmlPath,$sourcePlanPath,$sourceWorkPath -Force
    New-TestPdf (Join-Path $baseline 'manual.pdf') 15;Export-TestPdf (Join-Path $baseline 'application-info.docx') (Join-Path $baseline 'application-info.pdf')
    $qualityModule=Get-Module StandardDocumentQuality;$manualDocxPath=Join-Path $baseline 'manual.docx';$manualPdfPath=Join-Path $baseline 'manual.pdf';$manualDocHash=(Get-FileHash $manualDocxPath -Algorithm SHA256).Hash.ToLowerInvariant();$manualPdfMetric=& $qualityModule {param($path)Get-PdfQualityPageCount $path 'manual'} $manualPdfPath;& $qualityModule {param($hash,$metric)$script:ReferencePdfCache[$hash]=$metric} $manualDocHash $manualPdfMetric
    $receipt=Test-StandardDocumentSet -Facts $facts -DocumentRoot $baseline -ExpectedScreenshots $screenshots -SourcePlan $sourcePlan;Assert-Equal $receipt.status 'passed';Assert-Equal @($receipt.documents).Count 8;Assert-Match ($receipt|ConvertTo-Json -Depth 8) 'factsSha256';Assert-Equal (($receipt|ConvertTo-Json -Depth 8)-match[regex]::Escape($root)) $false;Assert-Equal $receipt.sourceSelectionSha256 ([string]$sourcePlan.selectionSha256)
    $reordered=[pscustomobject][ordered]@{screenshots=$facts.screenshots;evidence=$facts.evidence;source=$facts.source;workflows=$facts.workflows;commands=$facts.commands;roles=$facts.roles;entities=$facts.entities;modules=$facts.modules;software=$facts.software;templateId=$facts.templateId;factVersion=$facts.factVersion};$canonicalOriginal=& $qualityModule {param($value)ConvertTo-CanonicalQualityJson $value} $facts;$canonicalReordered=& $qualityModule {param($value)ConvertTo-CanonicalQualityJson $value} $reordered;Assert-Equal $canonicalOriginal $canonicalReordered
    $mappingPlan=$sourcePlan|ConvertTo-Json -Depth 10|ConvertFrom-Json;$mappingPlan.pages[0].mappings[0].path='D:/private/source.ts';$mappingPlan.pages[0].mappings[0].text='D:/private/source.ts';Assert-Throws {Test-StandardDocumentSet -Facts $facts -DocumentRoot $baseline -ExpectedScreenshots $screenshots -SourcePlan $mappingPlan|Out-Null} 'QUALITY_SOURCE_PLAN'
    $emptyFinalPlan=$sourcePlan|ConvertTo-Json -Depth 10|ConvertFrom-Json;$emptyFinalPlan.pages[-1].mappings=@();$emptyFinalPlan.pages[-1].lines=@();Assert-Throws {Test-StandardDocumentSet -Facts $facts -DocumentRoot $baseline -ExpectedScreenshots $screenshots -SourcePlan $emptyFinalPlan|Out-Null} 'QUALITY_SOURCE_PLAN'
    $cases=@(
        @('thin','introduction.docx',{param($p)New-TestDocx $p 3 (Content @('建设目的') 100 $name $version) -Headings $introHeadings},'QUALITY_INTRODUCTION_CHARACTERS'),
        @('forged-pages','introduction.docx',{param($p)New-TestDocx $p 3 (Content ($introHeadings+@('项目管理','项目任务','项目风险')) 1300 $name $version) -Headings $introHeadings -ActualPages 1},'QUALITY_INTRODUCTION_PAGE_METADATA'),
        @('table-free','runtime.docx',{param($p)New-TestDocx $p 3 (Content @('运行环境说明','安装准备','备份与恢复') 900 $name $version) -Headings @('运行环境说明','安装准备','备份与恢复')},'QUALITY_RUNTIME_TABLES'),
        @('image-free','prototype.docx',{param($p)New-TestDocx $p 6 (Content @('导航层级','列表、详情与表单','角色操作矩阵','业务流程','实体关系','项目','项目任务','项目风险') 1200 $name $version) -Headings @('导航层级','列表、详情与表单','角色操作矩阵','业务流程','实体关系')},'QUALITY_PROTOTYPE_MEDIA'),
        @('wrong-page','application-info.docx',{param($p)New-TestDocx $p 1 $applicationText -Tables 1 -Bookmarks $bookmarks -Headings @('计算机软件著作权登记申请信息')},'QUALITY_APPLICATION_INFO_PAGES'),
        @('wrong-title','introduction.docx',{param($p)New-TestDocx $p 3 (Content ($introHeadings+@('项目管理','项目任务','项目风险')) 1300 '错误软件名称' $version) -Headings $introHeadings},'QUALITY_INTRODUCTION_TITLE'),
        @('internal-id','manual.docx',{param($p)New-TestDocx $p 15 ((Content @('操作手册','完整业务流程','步骤 1','备份与恢复','项目管理','项目任务','项目风险') 3200 $name $version)+' project.create') -Tables 2 -Images $screenshots -Headings @('操作手册','备份与恢复') -WorkflowItems @('步骤 1 项目立项 项目信息完整 形成项目记录 信息错误时拒绝','步骤 2 任务执行 项目已经激活 形成任务进展 状态错误时拒绝')},'QUALITY_MANUAL_INTERNAL_ID'),
        @('field-id','manual.docx',{param($p)New-TestDocx $p 15 ((Content @('操作手册','完整业务流程','步骤 1','备份与恢复','项目管理','项目任务','项目风险') 3200 $name $version)+' project_code') -Tables 2 -Images $screenshots -Headings @('操作手册','备份与恢复') -WorkflowItems @('步骤 1 项目立项 项目信息完整 形成项目记录 信息错误时拒绝','步骤 2 任务执行 项目已经激活 形成任务进展 状态错误时拒绝')},'QUALITY_MANUAL_INTERNAL_ID'),
        @('local-path','manual.docx',{param($p)New-TestDocx $p 15 ((Content @('操作手册','完整业务流程','步骤 1','备份与恢复','项目管理','项目任务','项目风险') 3200 $name $version)+' D:/repo/private/file.txt') -Tables 2 -Images $screenshots -Headings @('操作手册','备份与恢复') -WorkflowItems @('步骤 1 项目立项 项目信息完整 形成项目记录 信息错误时拒绝','步骤 2 任务执行 项目已经激活 形成任务进展 状态错误时拒绝')},'QUALITY_MANUAL_FORBIDDEN_TEXT'),
        @('secret','manual.docx',{param($p)New-TestDocx $p 15 ((Content @('操作手册','完整业务流程','步骤 1','备份与恢复','项目管理','项目任务','项目风险') 3200 $name $version)+' api_key="SensitiveValue123"') -Tables 2 -Images $screenshots -Headings @('操作手册','备份与恢复') -WorkflowItems @('步骤 1 项目立项 项目信息完整 形成项目记录 信息错误时拒绝','步骤 2 任务执行 项目已经激活 形成任务进展 状态错误时拒绝')},'QUALITY_MANUAL_FORBIDDEN_TEXT'),
        @('hidden-path','manual.docx',{param($p)Add-TestAppProperty $p 'D:/private/hidden.txt'},'QUALITY_MANUAL_FORBIDDEN_TEXT'),
        @('external-path','manual.docx',{param($p)Add-TestExternalRelationship $p 'D:/private/external.txt'},'QUALITY_MANUAL_FORBIDDEN_TEXT'),
        @('instruction-path','manual.docx',{param($p)Add-TestInstructionText $p 'D:/private/instruction.txt'},'QUALITY_MANUAL_FORBIDDEN_TEXT'),
        @('docvar-path','manual.docx',{param($p)Set-TestDocxVariable $p 'HiddenPath' 'D:/private/docvar.txt'},'QUALITY_MANUAL_FORBIDDEN_TEXT'),
        @('identity-metadata','manual.docx',{param($p)Add-TestAppProperty $p 'Alice Applicant' 'Company'},'QUALITY_MANUAL_IDENTITY_METADATA'),
        @('source-secret','source.docx',{param($p)Add-TestAppProperty $p 'api_key="SensitiveValue123"'},'QUALITY_SOURCE_FORBIDDEN_TEXT'),
        @('source-missing-line','source.docx',{param($p)Remove-TestDocxParagraph $p 'line0001'},'QUALITY_SOURCE_CONTENT'),
        @('workflow-decoy','manual.docx',{param($p)New-TestDocx $p 15 (Content @('操作手册','完整业务流程','步骤 1','备份与恢复','项目管理','项目任务','项目风险') 3200 $name $version) -Tables 2 -Images $screenshots -Headings @('操作手册','备份与恢复') -WorkflowProse '项目立项 项目信息完整 形成项目记录 信息错误时拒绝 任务执行 项目已经激活 形成任务进展 状态错误时拒绝' -WorkflowItems @('无关编号一','无关编号二')},'QUALITY_MANUAL_WORKFLOW'),
        @('zero-width','introduction.docx',{param($p)$padding=$name+' V'+$version+' '+($introHeadings+@('项目管理','项目任务','项目风险')-join' ')+(([string][char]0x200B)*2000);New-TestDocx $p 3 $padding -Headings $introHeadings},'QUALITY_INTRODUCTION_CHARACTERS'),
        @('feature-decoy','feature-table.docx',{param($p)New-TestDocx $p 6 (Content @('软件功能表','项目管理','项目任务','项目风险') 2600 $name $version) -Tables 3 -Headings @('软件功能表')},'QUALITY_FEATURE_TABLE_MODULE_TABLES'),
        @('database-decoy','database-design.docx',{param($p)New-TestDocx $p 12 (Content @('数据库设计','核心数据字典','实体关系','项目','项目任务','项目风险') 3600 $name $version) -Tables 3 -Images @($diagrams[0]) -Headings @('数据库设计','核心数据字典','实体关系')},'QUALITY_DATABASE_DESIGN_ENTITY_TABLES'),
        @('duplicate-media','manual.docx',{param($p)New-TestDocx $p 15 (Content @('操作手册','完整业务流程','步骤 1','备份与恢复','项目管理','项目任务','项目风险') 3200 $name $version) -Tables 2 -Images (@($screenshots[0])*12) -Headings @('操作手册','备份与恢复') -WorkflowItems @('步骤 1 项目立项 项目信息完整 形成项目记录 信息错误时拒绝','步骤 2 任务执行 项目已经激活 形成任务进展 状态错误时拒绝')},'QUALITY_MANUAL_MEDIA_DUPLICATE'),
        @('blank-pdf','manual.pdf',{param($p)New-TestPdf $p 15 -Blank},'QUALITY_MANUAL_PDF_BLANK'),
        @('unrelated-pdf','manual.pdf',{param($p)New-TestPdf $p 15 -Variant},'QUALITY_MANUAL_PDF_BINDING'),
        @('subtle-pdf','manual.pdf',{param($p)New-TestPdf $p 15 -Variant},'QUALITY_MANUAL_PDF_BINDING'),
        @('source-digest','source.docx',{param($p)Set-TestDocxVariable $p 'SourceSelectionSha256' ('9'*64)},'QUALITY_SOURCE_DIGEST')
    )
    foreach($case in $cases){$caseRoot=Join-Path $root $case[0];Copy-Item -LiteralPath $baseline -Destination $caseRoot -Recurse;& $case[2] (Join-Path $caseRoot $case[1]);if($case[1]-eq'manual.docx'){$mutatedHash=(Get-FileHash (Join-Path $caseRoot 'manual.docx') -Algorithm SHA256).Hash.ToLowerInvariant();& $qualityModule {param($hash,$metric)$script:ReferencePdfCache[$hash]=$metric} $mutatedHash $manualPdfMetric};Assert-Throws {Test-StandardDocumentSet -Facts $facts -DocumentRoot $caseRoot -ExpectedScreenshots $screenshots -SourcePlan $sourcePlan|Out-Null} $case[3]}
    $supplemental=Join-Path $root 'supplemental';Copy-Item -LiteralPath $baseline -Destination $supplemental -Recurse;$extra=Join-Path $assets 'diagram-extra.png';New-Png $extra 18;New-TestDocx (Join-Path $supplemental 'prototype.docx') 6 (Content @('导航层级','列表、详情与表单','角色操作矩阵','业务流程','实体关系','项目','项目任务','项目风险') 1200 $name $version) -Tables 1 -Images (@($diagrams)+@($extra)) -Headings @('导航层级','列表、详情与表单','角色操作矩阵','业务流程','实体关系');Assert-Equal (Test-StandardDocumentSet -Facts $facts -DocumentRoot $supplemental -ExpectedScreenshots $screenshots -SourcePlan $sourcePlan).status 'passed'
}
finally{if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}}
