import { createHash } from 'node:crypto';
import { AppError } from '../../../../desktop-runtime/src/shared/errors';
import type { DomainCommandDefinition, DomainCommandExecutionContext, JsonObject } from '../../../src/runtime/types';
import type { InspectionAbnormalDto, InspectionArchiveBlocker } from '../../inspection_rectification/runtime/types';
import type { WorkOrderContext } from '../../work_order_service/runtime/types';
import { WorkOrderService } from '../../work_order_service/runtime/work-order-service';

export const INSPECTION_WORK_ORDER_COMMAND = 'inspection.work_order.create';
export interface InspectionWorkOrderConfig { readonly serviceCode:string;readonly priority:'low'|'normal'|'high'|'urgent' }
export type WorkOrderContextFactory=(execution:DomainCommandExecutionContext)=>WorkOrderContext;

function digest(payload:JsonObject):string{return createHash('sha256').update(JSON.stringify(payload)).digest('hex');}
function parse(payload:JsonObject):JsonObject{const keys=Object.keys(payload).sort();if(JSON.stringify(keys)!==JSON.stringify(['itemCode','priority','recordedBy','serviceCode','taskCode']))throw new AppError('VALIDATION_FAILED','Inspection work order command fields are invalid.');for(const key of['itemCode','recordedBy','serviceCode','taskCode'])if(typeof payload[key]!=='string'||!String(payload[key]).trim())throw new AppError('VALIDATION_FAILED',`${key} is required.`);if(!['low','normal','high','urgent'].includes(String(payload.priority)))throw new AppError('VALIDATION_FAILED','priority is invalid.');return payload;}

export function createInspectionWorkOrderCommand(contextFactory:WorkOrderContextFactory):DomainCommandDefinition{return Object.freeze({id:INSPECTION_WORK_ORDER_COMMAND,allowedSources:Object.freeze(['inspection_work_order_bridge']),parse,execute:(execution:DomainCommandExecutionContext,payload:JsonObject)=>{const payloadDigest=digest(payload);const existing=execution.connection.prepare('SELECT work_order_code,payload_digest FROM biz_inspection_work_order_link WHERE inspection_item_code=?').get(String(payload.itemCode))as{work_order_code:string;payload_digest:string}|undefined;if(existing){if(existing.payload_digest!==payloadDigest)throw new AppError('UNIQUE_CONFLICT','Inspection abnormality was already linked with different command data.');return Object.freeze({workOrderCode:existing.work_order_code});}const item=execution.connection.prepare('SELECT task_code,finding,disposition,result FROM biz_inspection_item WHERE code=?').get(String(payload.itemCode))as{task_code:string;finding:string|null;disposition:string|null;result:string}|undefined;if(!item||item.task_code!==payload.taskCode||item.result!=='abnormal')throw new AppError('INVALID_TRANSITION','Inspection item is not a matching abnormality.');const context=contextFactory(execution);const result=new WorkOrderService().create({title:`巡检异常 ${String(payload.itemCode)}`,description:`${item.finding??'巡检异常'}；${item.disposition??'待整改'}`,serviceCode:String(payload.serviceCode),priority:payload.priority as InspectionWorkOrderConfig['priority']},context);const code=`IWL-${payloadDigest.slice(0,20).toUpperCase()}`;execution.connection.prepare('INSERT INTO biz_inspection_work_order_link(code,inspection_task_code,inspection_item_code,work_order_code,payload_digest,created_at_business,version,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').run(code,String(payload.taskCode),String(payload.itemCode),result.workOrderCode,payloadDigest,context.now().toISOString(),context.now().toISOString(),context.now().toISOString());return Object.freeze({workOrderCode:result.workOrderCode});}});}

export function createInspectionWorkOrderAbnormalHandler(config:InspectionWorkOrderConfig){return(dto:InspectionAbnormalDto,bus:{invoke:Function})=>bus.invoke(INSPECTION_WORK_ORDER_COMMAND,{taskCode:dto.taskCode,itemCode:dto.itemCode,recordedBy:dto.recordedBy,serviceCode:config.serviceCode,priority:config.priority});}
export const inspectionWorkOrderAbnormalHandler=createInspectionWorkOrderAbnormalHandler({serviceCode:'SVC-RECTIFICATION',priority:'normal'});

export function createOpenRectificationBlocker():InspectionArchiveBlocker{return(taskId,connection)=>{const tasks=connection.find('inspection_task',{id:taskId});if(tasks.length===0)return{blocked:false,code:'TASK_NOT_FOUND',message:''};const taskCode=String(tasks[0]!.code),items=connection.find('inspection_item',{task_code:taskCode}).filter(item=>item.result==='abnormal');for(const item of items){const links=connection.find('inspection_work_order_link',{inspection_item_code:String(item.code)});if(links.length!==1)return{blocked:true,code:'ABNORMALITY_NOT_LINKED',message:'Inspection abnormality has no rectification work order.'};const orders=connection.find('work_order',{code:String(links[0]!.work_order_code)});if(orders.length!==1||orders[0]!.status!=='closed')return{blocked:true,code:'RECTIFICATION_WORK_ORDER_OPEN',message:'Rectification work order must be closed before inspection archive.'};}return{blocked:false,code:'RECTIFICATION_COMPLETE',message:''};};}
