import{AppError}from'../../../../desktop-runtime/src/shared/errors';import{assertApplicant,audit,readApplication,required,result}from'./internals';import*as approval from'./approval-commands';import type{ApplicationContext,ApplicationResult,ApproveNodeRequest,CreateApplicationRequest,RejectNodeRequest,ReviseApplicationRequest,SubmitApplicationRequest,UpdateDraftApplicationRequest,WithdrawApplicationRequest}from'./types';
import*as files from'./file-commands';import type{FinalizeFileVersionRequest,RegisterStagedFileRequest}from'./types';
import*as certificates from'./certificate-commands';import type{AcknowledgeReminderRequest,ArchiveApplicationRequest,CreateCertificateRequest,RefreshExpiryRemindersRequest,RenewCertificateRequest}from'./types';
export class ApplicationArchiveService{
 createApplication(request:CreateApplicationRequest,context:ApplicationContext):ApplicationResult{const permission='applications.create_application';context.requirePermission(context.actor,permission);if(!context.identityHasRole(context.actor.username,'application_applicant',context.connection))throw new AppError('PERMISSION_DENIED','Current identity is not an applicant.');const type=required(request.applicationType,'applicationType'),title=required(request.title,'title'),content=required(request.content,'content'),code=context.applicationCode(),now=context.now().toISOString();const inserted=context.connection.prepare("INSERT INTO biz_application (code,application_type,title,content,applicant_id,status,approval_round,current_node_code,submitted_at,approved_at,archived_at,version,created_at,updated_at) VALUES (?,?,?,?,?,'draft',0,NULL,NULL,NULL,NULL,1,?,?)").run(code,type,title,content,context.actor.username,now,now),id=Number(inserted.lastInsertRowid),row={id,code,application_type:type,title,content,applicant_id:context.actor.username,status:'draft' as const,approval_round:0,current_node_code:null,version:1};audit(context,permission,row,Object.freeze({code}));return result(row);}
 updateDraftApplication(request:UpdateDraftApplicationRequest,context:ApplicationContext):ApplicationResult{const permission='applications.update_draft';context.requirePermission(context.actor,permission);const row=readApplication(request.applicationId,context);assertApplicant(row,context);if(row.status!=='draft')throw new AppError('INVALID_TRANSITION','Only draft applications can be updated.');const type=required(request.applicationType,'applicationType'),title=required(request.title,'title'),content=required(request.content,'content');if(row.version!==request.expectedVersion)throw new AppError('VERSION_CONFLICT','Application version conflict.');const now=context.now().toISOString(),update=context.connection.prepare('UPDATE biz_application SET application_type=?,title=?,content=?,version=version+1,updated_at=? WHERE id=? AND version=?').run(type,title,content,now,row.id,request.expectedVersion);if(Number(update.changes)!==1)throw new AppError('VERSION_CONFLICT','Application version conflict.');audit(context,permission,row,Object.freeze({code:row.code}));return result(row,{version:row.version+1});}
 submitApplication(request:SubmitApplicationRequest,context:ApplicationContext){return approval.submitApplication(request,context);}
 approveCurrentNode(request:ApproveNodeRequest,context:ApplicationContext){return approval.approveCurrentNode(request,context);}
 rejectCurrentNode(request:RejectNodeRequest,context:ApplicationContext){return approval.rejectCurrentNode(request,context);}
 withdrawApplication(request:WithdrawApplicationRequest,context:ApplicationContext){return approval.withdrawApplication(request,context);}
 reviseApplication(request:ReviseApplicationRequest,context:ApplicationContext){return approval.reviseApplication(request,context);}
 registerStagedFile(request:RegisterStagedFileRequest,context:ApplicationContext){return files.registerStagedFile(request,context);}
 finalizeFileVersion(request:FinalizeFileVersionRequest,context:ApplicationContext){return files.finalizeFileVersion(request,context);}
 recoverStagedFiles(context:ApplicationContext){return files.recoverStagedFiles(context);}
 archiveApplication(request:ArchiveApplicationRequest,context:ApplicationContext){return certificates.archiveApplication(request,context);}
 createCertificate(request:CreateCertificateRequest,context:ApplicationContext){return certificates.createCertificate(request,context);}
 renewCertificate(request:RenewCertificateRequest,context:ApplicationContext){return certificates.renewCertificate(request,context);}
 refreshExpiryReminders(request:RefreshExpiryRemindersRequest,context:ApplicationContext){return certificates.refreshExpiryReminders(request,context);}
 acknowledgeReminder(request:AcknowledgeReminderRequest,context:ApplicationContext){return certificates.acknowledgeReminder(request,context);}
}
