import{createHash,randomUUID}from'node:crypto';import fs from'node:fs';import path from'node:path';import{AppError}from'../../../../desktop-runtime/src/shared/errors';import type{ArchiveFileInspection,ArchiveStore,StagedArchiveFile}from'./types';
function directory(target:string){const stat=fs.lstatSync(target);if(!stat.isDirectory()||stat.isSymbolicLink())throw new AppError('VALIDATION_FAILED','Archive directory must be a regular directory.');}
function noReparseAncestors(target:string){const resolved=path.resolve(target),root=path.parse(resolved).root;let current=root;for(const part of resolved.slice(root.length).split(path.sep).filter(Boolean)){current=path.join(current,part);if(!fs.existsSync(current))continue;const stat=fs.lstatSync(current);if(stat.isSymbolicLink())throw new AppError('VALIDATION_FAILED','Archive path cannot contain a reparse point.');}}
function inspection(target:string):ArchiveFileInspection{const bytes=fs.readFileSync(target),stat=fs.lstatSync(target);if(!stat.isFile()||stat.isSymbolicLink())throw new AppError('VALIDATION_FAILED','Archive file must be a regular file.');return Object.freeze({sha256:createHash('sha256').update(bytes).digest('hex'),sizeBytes:stat.size});}
export class ManagedArchiveStore implements ArchiveStore{readonly #root:string;readonly #staging:string;constructor(root:string,staging:string,options:{create?:boolean}={}){this.#root=path.resolve(root);this.#staging=path.resolve(staging);noReparseAncestors(this.#root);noReparseAncestors(this.#staging);if(options.create){fs.mkdirSync(this.#root,{recursive:true});fs.mkdirSync(this.#staging,{recursive:true});}noReparseAncestors(this.#root);noReparseAncestors(this.#staging);directory(this.#root);directory(this.#staging);if(fs.statSync(this.#root).dev!==fs.statSync(this.#staging).dev)throw new AppError('VALIDATION_FAILED','Archive roots must be on the same volume.');}
 stageSelectedFile(sourcePath:string):StagedArchiveFile{if(!path.isAbsolute(sourcePath))throw new AppError('VALIDATION_FAILED','Selected file path must be absolute.');const source=path.resolve(sourcePath);noReparseAncestors(source);const stat=fs.lstatSync(source);if(!stat.isFile()||stat.isSymbolicLink())throw new AppError('VALIDATION_FAILED','Selected file must be a regular file.');directory(this.#staging);const token=randomUUID().replaceAll('-',''),target=path.join(this.#staging,`${token}.stage`);fs.copyFileSync(source,target,fs.constants.COPYFILE_EXCL);const info=inspection(target);return Object.freeze({stageToken:token,originalName:path.basename(source),...info});}
 inspectStage(token:string){const target=this.#stagePath(token);if(!fs.existsSync(target))return null;return inspection(target);}
 readyRelativePath(code:string){if(!/^[A-Za-z0-9_-]{2,80}$/.test(code))throw new AppError('VALIDATION_FAILED','File version code is invalid.');return`files/${code}.bin`;}
 inspectReady(relativePath:string){const target=this.#readyPath(relativePath);if(!fs.existsSync(target))return null;return inspection(target);}
 promote(token:string,code:string){const source=this.#stagePath(token);if(!fs.existsSync(source))throw new AppError('NOT_FOUND','Staged file is missing.');const relativePath=this.readyRelativePath(code),target=this.#readyPath(relativePath),parent=path.dirname(target);noReparseAncestors(parent);fs.mkdirSync(parent,{recursive:true});noReparseAncestors(parent);directory(parent);try{fs.linkSync(source,target);}catch(error){const code=(error as NodeJS.ErrnoException).code;if(code==='EEXIST')throw new AppError('UNIQUE_CONFLICT','Ready archive file already exists.');if(code==='EXDEV')throw new AppError('VALIDATION_FAILED','Archive roots must be on the same volume.');throw error;}fs.unlinkSync(source);return Object.freeze({relativePath,...inspection(target)});}
 discardStage(token:string){const target=this.#stagePath(token);if(fs.existsSync(target))fs.rmSync(target,{force:true});}
 #stagePath(token:string){if(!/^[a-f0-9]{32}$/.test(token))throw new AppError('VALIDATION_FAILED','Stage token is invalid.');directory(this.#staging);const target=path.resolve(this.#staging,`${token}.stage`);if(!target.startsWith(`${this.#staging}${path.sep}`))throw new AppError('VALIDATION_FAILED','Stage path escapes its root.');return target;}
 #readyPath(relativePath:string){const parts=relativePath.split('/');if(path.isAbsolute(relativePath)||relativePath.includes('\\')||parts.some(part=>!part||part==='.'||part==='..'))throw new AppError('VALIDATION_FAILED','Ready path is invalid.');directory(this.#root);const target=path.resolve(this.#root,...parts);if(!target.startsWith(`${this.#root}${path.sep}`))throw new AppError('VALIDATION_FAILED','Ready path escapes its root.');let current=this.#root;parts.forEach((part,index)=>{current=path.join(current,part);if(!fs.existsSync(current))return;const stat=fs.lstatSync(current);if(stat.isSymbolicLink())throw new AppError('VALIDATION_FAILED','Ready path cannot contain a reparse point.');if(index<parts.length-1&&!stat.isDirectory())throw new AppError('VALIDATION_FAILED','Ready path parent must be a directory.');});return target;}}
