import{AppError}from'../../../../desktop-runtime/src/shared/errors';import type{ApplicationContext,ApplicationResult,ApplicationStatus}from'./types';
export type ApplicationRow={id:number;code:string;application_type:string;title:string;content:string;applicant_id:string;status:ApplicationStatus;approval_round:number;current_node_code:string|null;version:number};
export function required(value:string,field:string){const normalized=value.trim();if(!normalized)throw new AppError('VALIDATION_FAILED',`${field} is required.`,{fieldErrors:[{field,message:'Required.'}]});return normalized;}
export function strictDate(value:string,field:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new AppError('VALIDATION_FAILED',`${field} is invalid.`);const parsed=new Date(`${value}T00:00:00.000Z`);if(Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==value)throw new AppError('VALIDATION_FAILED',`${field} is invalid.`);return value;}
export function readApplication(id:number,context:ApplicationContext){const row=context.connection.prepare('SELECT id,code,application_type,title,content,applicant_id,status,approval_round,current_node_code,version FROM biz_application WHERE id=?').get(id)as ApplicationRow|undefined;if(!row)throw new AppError('NOT_FOUND','Application not found.');return row;}
export function assertApplicant(row:ApplicationRow,context:ApplicationContext){if(!context.identityHasRole(context.actor.username,'application_applicant',context.connection)||row.applicant_id!==context.actor.username)throw new AppError('PERMISSION_DENIED','Current identity is not the application owner.');}
export function result(row:ApplicationRow,changes:Partial<Pick<ApplicationRow,'status'|'approval_round'|'current_node_code'|'version'>>={}):ApplicationResult{return Object.freeze({applicationId:row.id,applicationCode:row.code,status:changes.status??row.status,approvalRound:changes.approval_round??row.approval_round,currentNodeCode:changes.current_node_code===undefined?row.current_node_code:changes.current_node_code,version:changes.version??row.version});}
export function appendRecord(context:ApplicationContext,row:ApplicationRow,nodeCode:string|null,round:number,action:'submitted'|'approved'|'rejected'|'withdrawn'|'archived',comment:string|null){const code=context.recordCode(),now=context.now().toISOString();context.connection.prepare('INSERT INTO biz_approval_record (code,application_code,node_code,approval_round,action,actor_id,comment,occurred_at,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,1,?,?)').run(code,row.code,nodeCode,round,action,context.actor.username,comment,now,now,now);return code;}
export function audit(context:ApplicationContext,permission:string,row:ApplicationRow,details:Readonly<Record<string,unknown>>){context.appendAudit(context.connection,Object.freeze({actor:context.actor,permission,entityId:'application',recordId:row.id,result:'success',details}));}
