import { AppError } from '../../../../desktop-runtime/src/shared/errors'; import type { InventoryContext,MaterialInput,MaterialResult,UpdateMaterialRequest,UpdateWarehouseRequest,WarehouseInput,WarehouseResult } from './types';
function required(value:string,field:string){const x=value.trim();if(!x)throw new AppError('VALIDATION_FAILED',`${field} is required.`,{fieldErrors:[{field,message:'Required.'}]});return x;}
function nonnegative(value:number,field:string){if(!Number.isSafeInteger(value)||value<0)throw new AppError('VALIDATION_FAILED',`${field} must be a non-negative integer.`);return value;}
function admin(context:InventoryContext){if(!context.identityHasRole(context.actor.username,'inventory_admin',context.connection))throw new AppError('PERMISSION_DENIED','Current identity is not an inventory administrator.');}
export class InventoryService{
 createMaterial(request:MaterialInput,context:InventoryContext):MaterialResult{const permission='materials.create_material';context.requirePermission(context.actor,permission);admin(context);const name=required(request.name,'name'),unit=required(request.unit,'unit'),days=nonnegative(request.expiryWarningDays,'expiryWarningDays'),code=context.materialCode(),now=context.now().toISOString();let id:number;try{id=Number(context.connection.prepare('INSERT INTO biz_material (code,name,unit,expiry_warning_days,active,version,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?)').run(code,name,unit,days,request.active?1:0,now,now).lastInsertRowid);}catch(e){if(e instanceof Error&&/UNIQUE/.test(e.message))throw new AppError('UNIQUE_CONFLICT','Material code exists.');throw e;}context.appendAudit(context.connection,Object.freeze({actor:context.actor,permission,entityId:'material',recordId:id,result:'success',details:Object.freeze({code})}));return Object.freeze({materialId:id,materialCode:code,version:1,expiryWarningDays:days,active:request.active});}
 updateMaterial(request:UpdateMaterialRequest,context:InventoryContext):MaterialResult{const permission='materials.update_material';context.requirePermission(context.actor,permission);admin(context);const row=context.connection.prepare('SELECT id,code,version FROM biz_material WHERE id=?').get(request.materialId) as {id:number;code:string;version:number}|undefined;if(!row)throw new AppError('NOT_FOUND','Material not found.');if(row.version!==request.expectedVersion)throw new AppError('VERSION_CONFLICT','Material version conflict.');const name=required(request.name,'name'),unit=required(request.unit,'unit'),days=nonnegative(request.expiryWarningDays,'expiryWarningDays'),now=context.now().toISOString();const u=context.connection.prepare('UPDATE biz_material SET name=?,unit=?,expiry_warning_days=?,active=?,version=version+1,updated_at=? WHERE id=? AND version=?').run(name,unit,days,request.active?1:0,now,row.id,request.expectedVersion);if(Number(u.changes)!==1)throw new AppError('VERSION_CONFLICT','Material version conflict.');context.appendAudit(context.connection,Object.freeze({actor:context.actor,permission,entityId:'material',recordId:row.id,result:'success',details:Object.freeze({code:row.code})}));return Object.freeze({materialId:row.id,materialCode:row.code,version:row.version+1,expiryWarningDays:days,active:request.active});}
 createWarehouse(request:WarehouseInput,context:InventoryContext):WarehouseResult{const permission='warehouses.create_warehouse';context.requirePermission(context.actor,permission);admin(context);const name=required(request.name,'name'),code=context.warehouseCode(),now=context.now().toISOString();const id=Number(context.connection.prepare('INSERT INTO biz_warehouse (code,name,active,version,created_at,updated_at) VALUES (?,?,?,1,?,?)').run(code,name,request.active?1:0,now,now).lastInsertRowid);context.appendAudit(context.connection,Object.freeze({actor:context.actor,permission,entityId:'warehouse',recordId:id,result:'success',details:Object.freeze({code})}));return Object.freeze({warehouseId:id,warehouseCode:code,version:1,active:request.active});}
 updateWarehouse(request:UpdateWarehouseRequest,context:InventoryContext):WarehouseResult{const permission='warehouses.update_warehouse';context.requirePermission(context.actor,permission);admin(context);const row=context.connection.prepare('SELECT id,code,version FROM biz_warehouse WHERE id=?').get(request.warehouseId) as {id:number;code:string;version:number}|undefined;if(!row)throw new AppError('NOT_FOUND','Warehouse not found.');if(row.version!==request.expectedVersion)throw new AppError('VERSION_CONFLICT','Warehouse version conflict.');const name=required(request.name,'name'),now=context.now().toISOString();const u=context.connection.prepare('UPDATE biz_warehouse SET name=?,active=?,version=version+1,updated_at=? WHERE id=? AND version=?').run(name,request.active?1:0,now,row.id,request.expectedVersion);if(Number(u.changes)!==1)throw new AppError('VERSION_CONFLICT','Warehouse version conflict.');context.appendAudit(context.connection,Object.freeze({actor:context.actor,permission,entityId:'warehouse',recordId:row.id,result:'success',details:Object.freeze({code:row.code})}));return Object.freeze({warehouseId:row.id,warehouseCode:row.code,version:row.version+1,active:request.active});}
}
