import { useState } from 'react';
import type { DomainActionDto, EntityRecordDto } from '../../shared/dto';
import { unwrap } from '../utils';

interface Field { readonly id:string;readonly label:string;readonly type?:'text'|'number'|'datetime'|'select';readonly options?:readonly string[];readonly initial?:string }
const LABELS:Readonly<Record<string,string>>={
  'asset.change_status':'变更状态','asset.work_order.create':'创建工单','asset.inspection.plan.create':'创建巡检计划','asset.inspection.task.create':'创建巡检任务',
  'inspection.assign':'调整执行人','inspection.start':'开始巡检','inspection.record':'记录检查结果','inspection.submit':'提交复核','inspection.reject':'驳回巡检','inspection.archive':'归档巡检',
  'work_order.dispatch':'分派工单','work_order.accept':'受理工单','work_order.add_processing_record':'填写处理记录','work_order.submit_resolution':'提交解决','work_order.reject_review':'驳回返工','work_order.approve_close':'复核关闭'
};
const FIELDS:Readonly<Record<string,readonly Field[]>>={
  'asset.change_status':[{id:'nextStatus',label:'目标状态',type:'select',options:['active','maintenance','inactive']},{id:'reason',label:'变更原因'}],
  'asset.work_order.create':[{id:'title',label:'工单标题'},{id:'description',label:'问题描述'},{id:'serviceCode',label:'服务编码',initial:'SVC-RECTIFICATION'},{id:'priority',label:'优先级',type:'select',options:['low','normal','high','urgent'],initial:'normal'}],
  'asset.inspection.plan.create':[{id:'name',label:'计划名称'},{id:'cycleDays',label:'周期天数',type:'number',initial:'1'},{id:'instructions',label:'执行说明'}],
  'asset.inspection.task.create':[{id:'title',label:'任务标题'},{id:'executorId',label:'执行账号',initial:'operator'},{id:'scheduledAt',label:'计划时间',type:'datetime'},{id:'itemName',label:'检查项'},{id:'itemStandard',label:'检查标准'}],
  'inspection.assign':[{id:'executorId',label:'执行账号',initial:'operator'},{id:'reason',label:'调整原因'}],
  'inspection.record':[{id:'itemId',label:'检查项 ID',type:'number'},{id:'result',label:'检查结果',type:'select',options:['normal','abnormal'],initial:'normal'},{id:'finding',label:'异常描述'},{id:'disposition',label:'处置说明'}],
  'inspection.reject':[{id:'reason',label:'驳回原因'}],'inspection.archive':[{id:'comment',label:'归档说明'}],
  'work_order.dispatch':[{id:'handlerId',label:'处理账号',initial:'operator'},{id:'reason',label:'分派说明'}],
  'work_order.add_processing_record':[{id:'content',label:'处理记录'}],'work_order.submit_resolution':[{id:'resolution',label:'解决说明'}],
  'work_order.reject_review':[{id:'reason',label:'驳回原因'}],'work_order.approve_close':[{id:'comment',label:'复核说明'}]
};
function base(id:string,record:EntityRecordDto){if(id.startsWith('work_order.'))return{workOrderId:record.id,expectedVersion:record.version};if(id.startsWith('inspection.'))return{taskId:record.id,expectedTaskVersion:record.version};if(id==='asset.change_status')return{assetId:record.id,expectedVersion:record.version};if(id==='asset.work_order.create'||id==='asset.inspection.plan.create')return{assetId:record.id};if(id==='asset.inspection.task.create')return{planCode:String(record.values.code)};return{};}
export function DomainActions({token,entityId,record,actions,onComplete}:{token:string;entityId:string;record:EntityRecordDto;actions:readonly DomainActionDto[];onComplete:()=>void}){const noInput=new Set(['inspection.start','inspection.submit','work_order.accept']);const available=actions.filter(x=>x.entityId===entityId&&(Boolean(FIELDS[x.id])||noInput.has(x.id)));const[selected,setSelected]=useState<DomainActionDto|null>(null),[values,setValues]=useState<Record<string,string>>({}),[error,setError]=useState('');if(available.length===0)return null;async function run(action:DomainActionDto){const fields=FIELDS[action.id]??[];if(fields.length&&selected?.id!==action.id){setSelected(action);setValues(Object.fromEntries(fields.map(x=>[x.id,x.initial??''])));setError('');return;}try{const input:Record<string,unknown>={...base(action.id,record)};for(const field of fields)input[field.id]=field.type==='number'?Number(values[field.id]):field.type==='datetime'?new Date(values[field.id]!).toISOString():values[field.id];if(action.id==='asset.inspection.plan.create')input.active=true;if(action.id==='asset.inspection.task.create'){input.items=[{name:input.itemName,standard:input.itemStandard}];delete input.itemName;delete input.itemStandard;}if(action.id==='inspection.record'&&input.result==='normal'){input.finding=null;input.disposition=null;}unwrap(await window.businessApi.domain.execute(token,action.id,input));setSelected(null);onComplete();}catch{setError('操作未完成，请检查输入和当前状态');}}
return <section className="domain-actions" aria-label="领域操作"><div className="action-row">{available.map(action=><button key={action.id} className="secondary-button" onClick={()=>void run(action)}>{LABELS[action.id]??action.label}</button>)}</div>{selected&&<form onSubmit={e=>{e.preventDefault();void run(selected);}}><h4>{LABELS[selected.id]??selected.label}</h4>{(FIELDS[selected.id]??[]).map(field=><label key={field.id}>{field.label}{field.type==='select'?<select value={values[field.id]??''} onChange={e=>setValues({...values,[field.id]:e.target.value})}>{field.options?.map(x=><option key={x}>{x}</option>)}</select>:<input type={field.type==='number'?'number':field.type==='datetime'?'datetime-local':'text'} value={values[field.id]??''} onChange={e=>setValues({...values,[field.id]:e.target.value})} required/>}</label>)}{error&&<p className="error-text">{error}</p>}<div className="action-row"><button className="primary-button" type="submit">确认</button><button className="secondary-button" type="button" onClick={()=>setSelected(null)}>取消</button></div></form>}</section>;}
